# coding: utf-8

"""
    BambooHR API

    This is the majority of the API requests including some that are not documented.  http://www.bamboohr.com/api/documentation/

    The version of the OpenAPI document: v1
    Generated by: https://konfigthis.com
"""

import unittest

import os
from pprint import pprint
from bamboo_hr_python_sdk import BambooHr

class TestSimple(unittest.TestCase):
    def setUp(self):
        pass

    def test_client(self):
        bamboohr = BambooHr(
        
            client_id = 'YOUR_CLIENT_ID',
            client_secret = 'YOUR_CLIENT_SECRET',,
        
            username = 'YOUR_USERNAME',
            password = 'YOUR_PASSWORD'
        )
        self.assertIsNotNone(bamboohr)

    def tearDown(self):
        pass


if __name__ == "__main__":
    unittest.main()
