# coding: utf-8

"""
    BambooHR API

    This is the majority of the API requests including some that are not documented.  http://www.bamboohr.com/api/documentation/

    The version of the OpenAPI document: v1
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from bamboo_hr_python_sdk import schemas  # noqa: F401


class ApplicantTrackingListApplicationsResponse(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        class properties:
            paginationComplete = schemas.BoolSchema
        
            @staticmethod
            def applications() -> typing.Type['ApplicantTrackingListApplicationsResponseApplications']:
                return ApplicantTrackingListApplicationsResponseApplications
            nextPageUrl = schemas.StrSchema
            __annotations__ = {
                "paginationComplete": paginationComplete,
                "applications": applications,
                "nextPageUrl": nextPageUrl,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["paginationComplete"]) -> MetaOapg.properties.paginationComplete: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["applications"]) -> 'ApplicantTrackingListApplicationsResponseApplications': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["nextPageUrl"]) -> MetaOapg.properties.nextPageUrl: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["paginationComplete", "applications", "nextPageUrl", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["paginationComplete"]) -> typing.Union[MetaOapg.properties.paginationComplete, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["applications"]) -> typing.Union['ApplicantTrackingListApplicationsResponseApplications', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["nextPageUrl"]) -> typing.Union[MetaOapg.properties.nextPageUrl, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["paginationComplete", "applications", "nextPageUrl", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        paginationComplete: typing.Union[MetaOapg.properties.paginationComplete, bool, schemas.Unset] = schemas.unset,
        applications: typing.Union['ApplicantTrackingListApplicationsResponseApplications', schemas.Unset] = schemas.unset,
        nextPageUrl: typing.Union[MetaOapg.properties.nextPageUrl, str, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'ApplicantTrackingListApplicationsResponse':
        return super().__new__(
            cls,
            *args,
            paginationComplete=paginationComplete,
            applications=applications,
            nextPageUrl=nextPageUrl,
            _configuration=_configuration,
            **kwargs,
        )

from bamboo_hr_python_sdk.model.applicant_tracking_list_applications_response_applications import ApplicantTrackingListApplicationsResponseApplications
