# coding: utf-8

"""
    BambooHR API

    This is the majority of the API requests including some that are not documented.  http://www.bamboohr.com/api/documentation/

    The version of the OpenAPI document: v1
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from bamboo_hr_python_sdk import schemas  # noqa: F401


class BenefitGroupPlanCost(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        class properties:
            benefitGroupPlanId = schemas.StrSchema
            benefitPlanCoverageId = schemas.StrSchema
            employeeCost = schemas.StrSchema
            companyCost = schemas.StrSchema
            startDate = schemas.StrSchema
            endDate = schemas.StrSchema
            __annotations__ = {
                "benefitGroupPlanId": benefitGroupPlanId,
                "benefitPlanCoverageId": benefitPlanCoverageId,
                "employeeCost": employeeCost,
                "companyCost": companyCost,
                "startDate": startDate,
                "endDate": endDate,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["benefitGroupPlanId"]) -> MetaOapg.properties.benefitGroupPlanId: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["benefitPlanCoverageId"]) -> MetaOapg.properties.benefitPlanCoverageId: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["employeeCost"]) -> MetaOapg.properties.employeeCost: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["companyCost"]) -> MetaOapg.properties.companyCost: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["startDate"]) -> MetaOapg.properties.startDate: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["endDate"]) -> MetaOapg.properties.endDate: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["benefitGroupPlanId", "benefitPlanCoverageId", "employeeCost", "companyCost", "startDate", "endDate", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["benefitGroupPlanId"]) -> typing.Union[MetaOapg.properties.benefitGroupPlanId, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["benefitPlanCoverageId"]) -> typing.Union[MetaOapg.properties.benefitPlanCoverageId, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["employeeCost"]) -> typing.Union[MetaOapg.properties.employeeCost, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["companyCost"]) -> typing.Union[MetaOapg.properties.companyCost, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["startDate"]) -> typing.Union[MetaOapg.properties.startDate, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["endDate"]) -> typing.Union[MetaOapg.properties.endDate, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["benefitGroupPlanId", "benefitPlanCoverageId", "employeeCost", "companyCost", "startDate", "endDate", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        benefitGroupPlanId: typing.Union[MetaOapg.properties.benefitGroupPlanId, str, schemas.Unset] = schemas.unset,
        benefitPlanCoverageId: typing.Union[MetaOapg.properties.benefitPlanCoverageId, str, schemas.Unset] = schemas.unset,
        employeeCost: typing.Union[MetaOapg.properties.employeeCost, str, schemas.Unset] = schemas.unset,
        companyCost: typing.Union[MetaOapg.properties.companyCost, str, schemas.Unset] = schemas.unset,
        startDate: typing.Union[MetaOapg.properties.startDate, str, schemas.Unset] = schemas.unset,
        endDate: typing.Union[MetaOapg.properties.endDate, str, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'BenefitGroupPlanCost':
        return super().__new__(
            cls,
            *args,
            benefitGroupPlanId=benefitGroupPlanId,
            benefitPlanCoverageId=benefitPlanCoverageId,
            employeeCost=employeeCost,
            companyCost=companyCost,
            startDate=startDate,
            endDate=endDate,
            _configuration=_configuration,
            **kwargs,
        )
