# coding: utf-8

"""
    BambooHR API

    This is the majority of the API requests including some that are not documented.  http://www.bamboohr.com/api/documentation/

    The version of the OpenAPI document: v1
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from bamboo_hr_python_sdk import schemas  # noqa: F401


class EmployeeBenefitFiltersFilters(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)

    At least one filter is required
    """


    class MetaOapg:
        
        class properties:
            employeeId = schemas.IntSchema
            companyBenefitId = schemas.IntSchema
            enrollmentStatusEffectiveDate = schemas.DateSchema
            __annotations__ = {
                "employeeId": employeeId,
                "companyBenefitId": companyBenefitId,
                "enrollmentStatusEffectiveDate": enrollmentStatusEffectiveDate,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["employeeId"]) -> MetaOapg.properties.employeeId: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["companyBenefitId"]) -> MetaOapg.properties.companyBenefitId: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["enrollmentStatusEffectiveDate"]) -> MetaOapg.properties.enrollmentStatusEffectiveDate: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["employeeId", "companyBenefitId", "enrollmentStatusEffectiveDate", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["employeeId"]) -> typing.Union[MetaOapg.properties.employeeId, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["companyBenefitId"]) -> typing.Union[MetaOapg.properties.companyBenefitId, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["enrollmentStatusEffectiveDate"]) -> typing.Union[MetaOapg.properties.enrollmentStatusEffectiveDate, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["employeeId", "companyBenefitId", "enrollmentStatusEffectiveDate", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        employeeId: typing.Union[MetaOapg.properties.employeeId, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        companyBenefitId: typing.Union[MetaOapg.properties.companyBenefitId, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        enrollmentStatusEffectiveDate: typing.Union[MetaOapg.properties.enrollmentStatusEffectiveDate, str, date, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'EmployeeBenefitFiltersFilters':
        return super().__new__(
            cls,
            *args,
            employeeId=employeeId,
            companyBenefitId=companyBenefitId,
            enrollmentStatusEffectiveDate=enrollmentStatusEffectiveDate,
            _configuration=_configuration,
            **kwargs,
        )
