# coding: utf-8

"""
    BambooHR API

    This is the majority of the API requests including some that are not documented.  http://www.bamboohr.com/api/documentation/

    The version of the OpenAPI document: v1
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from bamboo_hr_python_sdk import schemas  # noqa: F401


class EmployeePaystubTaxesItem(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        class properties:
            externalTaxId = schemas.StrSchema
            taxDescription = schemas.StrSchema
            taxAmount = schemas.StrSchema
            ytdTaxAmount = schemas.StrSchema
            __annotations__ = {
                "externalTaxId": externalTaxId,
                "taxDescription": taxDescription,
                "taxAmount": taxAmount,
                "ytdTaxAmount": ytdTaxAmount,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["externalTaxId"]) -> MetaOapg.properties.externalTaxId: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["taxDescription"]) -> MetaOapg.properties.taxDescription: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["taxAmount"]) -> MetaOapg.properties.taxAmount: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["ytdTaxAmount"]) -> MetaOapg.properties.ytdTaxAmount: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["externalTaxId", "taxDescription", "taxAmount", "ytdTaxAmount", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["externalTaxId"]) -> typing.Union[MetaOapg.properties.externalTaxId, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["taxDescription"]) -> typing.Union[MetaOapg.properties.taxDescription, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["taxAmount"]) -> typing.Union[MetaOapg.properties.taxAmount, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["ytdTaxAmount"]) -> typing.Union[MetaOapg.properties.ytdTaxAmount, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["externalTaxId", "taxDescription", "taxAmount", "ytdTaxAmount", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        externalTaxId: typing.Union[MetaOapg.properties.externalTaxId, str, schemas.Unset] = schemas.unset,
        taxDescription: typing.Union[MetaOapg.properties.taxDescription, str, schemas.Unset] = schemas.unset,
        taxAmount: typing.Union[MetaOapg.properties.taxAmount, str, schemas.Unset] = schemas.unset,
        ytdTaxAmount: typing.Union[MetaOapg.properties.ytdTaxAmount, str, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'EmployeePaystubTaxesItem':
        return super().__new__(
            cls,
            *args,
            externalTaxId=externalTaxId,
            taxDescription=taxDescription,
            taxAmount=taxAmount,
            ytdTaxAmount=ytdTaxAmount,
            _configuration=_configuration,
            **kwargs,
        )
