# coding: utf-8

"""
    BambooHR API

    This is the majority of the API requests including some that are not documented.  http://www.bamboohr.com/api/documentation/

    The version of the OpenAPI document: v1
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from bamboo_hr_python_sdk import schemas  # noqa: F401


class GoalsGetAllAggregateInfo200ResponseCommentsItem(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        class properties:
            goalId = schemas.IntSchema
            commentCount = schemas.IntSchema
            __annotations__ = {
                "goalId": goalId,
                "commentCount": commentCount,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["goalId"]) -> MetaOapg.properties.goalId: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["commentCount"]) -> MetaOapg.properties.commentCount: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["goalId", "commentCount", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["goalId"]) -> typing.Union[MetaOapg.properties.goalId, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["commentCount"]) -> typing.Union[MetaOapg.properties.commentCount, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["goalId", "commentCount", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        goalId: typing.Union[MetaOapg.properties.goalId, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        commentCount: typing.Union[MetaOapg.properties.commentCount, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'GoalsGetAllAggregateInfo200ResponseCommentsItem':
        return super().__new__(
            cls,
            *args,
            goalId=goalId,
            commentCount=commentCount,
            _configuration=_configuration,
            **kwargs,
        )
