# coding: utf-8

"""
    BambooHR API

    This is the majority of the API requests including some that are not documented.  http://www.bamboohr.com/api/documentation/

    The version of the OpenAPI document: v1
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from bamboo_hr_python_sdk import schemas  # noqa: F401


class TimeTrackingApproveEmployeeTimesheetsRequest1(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        class properties:
        
            @staticmethod
            def clockOuts() -> typing.Type['TimeTrackingApproveEmployeeTimesheetsRequest1ClockOuts']:
                return TimeTrackingApproveEmployeeTimesheetsRequest1ClockOuts
            __annotations__ = {
                "clockOuts": clockOuts,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["clockOuts"]) -> 'TimeTrackingApproveEmployeeTimesheetsRequest1ClockOuts': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["clockOuts", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["clockOuts"]) -> typing.Union['TimeTrackingApproveEmployeeTimesheetsRequest1ClockOuts', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["clockOuts", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        clockOuts: typing.Union['TimeTrackingApproveEmployeeTimesheetsRequest1ClockOuts', schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'TimeTrackingApproveEmployeeTimesheetsRequest1':
        return super().__new__(
            cls,
            *args,
            clockOuts=clockOuts,
            _configuration=_configuration,
            **kwargs,
        )

from bamboo_hr_python_sdk.model.time_tracking_approve_employee_timesheets_request1_clock_outs import TimeTrackingApproveEmployeeTimesheetsRequest1ClockOuts
