import typing_extensions

from bamboo_hr_python_sdk.paths import PathValues
from bamboo_hr_python_sdk.apis.paths.company_domain_v1_employees_directory import CompanyDomainV1EmployeesDirectory
from bamboo_hr_python_sdk.apis.paths.company_domain_v1_employees_files_categories import CompanyDomainV1EmployeesFilesCategories
from bamboo_hr_python_sdk.apis.paths.company_domain_v1_employees_id_files_file_id import CompanyDomainV1EmployeesIdFilesFileId
from bamboo_hr_python_sdk.apis.paths.company_domain_v1_employees_id_files import CompanyDomainV1EmployeesIdFiles
from bamboo_hr_python_sdk.apis.paths.company_domain_v1_files_categories import CompanyDomainV1FilesCategories
from bamboo_hr_python_sdk.apis.paths.company_domain_v1_files_file_id import CompanyDomainV1FilesFileId
from bamboo_hr_python_sdk.apis.paths.company_domain_v1_files import CompanyDomainV1Files
from bamboo_hr_python_sdk.apis.paths.company_domain_v1_reports_id import CompanyDomainV1ReportsId
from bamboo_hr_python_sdk.apis.paths.company_domain_v1_reports_custom import CompanyDomainV1ReportsCustom
from bamboo_hr_python_sdk.apis.paths.company_domain_v1_employees_id_tables_table import CompanyDomainV1EmployeesIdTablesTable
from bamboo_hr_python_sdk.apis.paths.company_domain_v1_employees_id_tables_table_row_id import CompanyDomainV1EmployeesIdTablesTableRowId
from bamboo_hr_python_sdk.apis.paths.company_domain_v1_1_employees_id_tables_table_row_id import CompanyDomainV11EmployeesIdTablesTableRowId
from bamboo_hr_python_sdk.apis.paths.company_domain_v1_1_employees_id_tables_table import CompanyDomainV11EmployeesIdTablesTable
from bamboo_hr_python_sdk.apis.paths.company_domain_v1_employees_changed_tables_table import CompanyDomainV1EmployeesChangedTablesTable
from bamboo_hr_python_sdk.apis.paths.company_domain_v1_meta_lists_list_field_id import CompanyDomainV1MetaListsListFieldId
from bamboo_hr_python_sdk.apis.paths.company_domain_v1_employees_employee_id_time_off_request import CompanyDomainV1EmployeesEmployeeIdTimeOffRequest
from bamboo_hr_python_sdk.apis.paths.company_domain_v1_time_off_requests_request_id_status import CompanyDomainV1TimeOffRequestsRequestIdStatus
from bamboo_hr_python_sdk.apis.paths.company_domain_v1_employees_employee_id_time_off_policies import CompanyDomainV1EmployeesEmployeeIdTimeOffPolicies
from bamboo_hr_python_sdk.apis.paths.company_domain_v1_1_employees_employee_id_time_off_policies import CompanyDomainV11EmployeesEmployeeIdTimeOffPolicies
from bamboo_hr_python_sdk.apis.paths.company_domain_v1_employees_employee_id_time_off_calculator import CompanyDomainV1EmployeesEmployeeIdTimeOffCalculator
from bamboo_hr_python_sdk.apis.paths.company_domain_v1_employees_employee_id_photo_size import CompanyDomainV1EmployeesEmployeeIdPhotoSize
from bamboo_hr_python_sdk.apis.paths.company_domain_v1_employees_employee_id_photo import CompanyDomainV1EmployeesEmployeeIdPhoto
from bamboo_hr_python_sdk.apis.paths.company_domain_v1_employees_changed import CompanyDomainV1EmployeesChanged
from bamboo_hr_python_sdk.apis.paths.company_domain_v1_login import CompanyDomainV1Login
from bamboo_hr_python_sdk.apis.paths.company_domain_v1_benefits_settings_deduction_types_all import CompanyDomainV1BenefitsSettingsDeductionTypesAll
from bamboo_hr_python_sdk.apis.paths.company_domain_v1_benefit_company_benefit import CompanyDomainV1BenefitCompanyBenefit
from bamboo_hr_python_sdk.apis.paths.company_domain_v1_benefit_company_benefit_id import CompanyDomainV1BenefitCompanyBenefitId
from bamboo_hr_python_sdk.apis.paths.company_domain_v1_benefit_company_benefit_type import CompanyDomainV1BenefitCompanyBenefitType
from bamboo_hr_python_sdk.apis.paths.company_domain_v1_benefit_employee_benefit import CompanyDomainV1BenefitEmployeeBenefit
from bamboo_hr_python_sdk.apis.paths.company_domain_v1_benefitcoverages import CompanyDomainV1Benefitcoverages
from bamboo_hr_python_sdk.apis.paths.company_domain_v1_employeedependents_id import CompanyDomainV1EmployeedependentsId
from bamboo_hr_python_sdk.apis.paths.company_domain_v1_employeedependents import CompanyDomainV1Employeedependents
from bamboo_hr_python_sdk.apis.paths.company_domain_v1_benefitplans import CompanyDomainV1Benefitplans
from bamboo_hr_python_sdk.apis.paths.company_domain_v1_benefitplancoverages import CompanyDomainV1Benefitplancoverages
from bamboo_hr_python_sdk.apis.paths.company_domain_v1_benefitgroups import CompanyDomainV1Benefitgroups
from bamboo_hr_python_sdk.apis.paths.company_domain_v1_benefitgroupemployees import CompanyDomainV1Benefitgroupemployees
from bamboo_hr_python_sdk.apis.paths.company_domain_v1_benefitgroupplans import CompanyDomainV1Benefitgroupplans
from bamboo_hr_python_sdk.apis.paths.company_domain_v1_benefitgroupplancosts import CompanyDomainV1Benefitgroupplancosts
from bamboo_hr_python_sdk.apis.paths.company_domain_v1_employee_deductions_id import CompanyDomainV1EmployeeDeductionsId
from bamboo_hr_python_sdk.apis.paths.company_domain_v1_employee_plans_id import CompanyDomainV1EmployeePlansId
from bamboo_hr_python_sdk.apis.paths.company_domain_v1_payroll_deductions_id import CompanyDomainV1PayrollDeductionsId
from bamboo_hr_python_sdk.apis.paths.company_domain_v1_employee_withholding_id import CompanyDomainV1EmployeeWithholdingId
from bamboo_hr_python_sdk.apis.paths.company_domain_v1_employee_direct_deposit_accounts_id import CompanyDomainV1EmployeeDirectDepositAccountsId
from bamboo_hr_python_sdk.apis.paths.company_domain_v1_employee_unpaid_pay_stubs_id import CompanyDomainV1EmployeeUnpaidPayStubsId
from bamboo_hr_python_sdk.apis.paths.company_domain_v1_employee_unpaid_pay_stubs import CompanyDomainV1EmployeeUnpaidPayStubs
from bamboo_hr_python_sdk.apis.paths.company_domain_v1_employee_pay_stub_id import CompanyDomainV1EmployeePayStubId
from bamboo_hr_python_sdk.apis.paths.company_domain_v1_employee_pay_stub import CompanyDomainV1EmployeePayStub
from bamboo_hr_python_sdk.apis.paths.company_domain_v1_timetracking_record_id import CompanyDomainV1TimetrackingRecordId
from bamboo_hr_python_sdk.apis.paths.company_domain_v1_timetracking_add import CompanyDomainV1TimetrackingAdd
from bamboo_hr_python_sdk.apis.paths.company_domain_v1_timetracking_adjust import CompanyDomainV1TimetrackingAdjust
from bamboo_hr_python_sdk.apis.paths.company_domain_v1_timetracking_delete_id import CompanyDomainV1TimetrackingDeleteId
from bamboo_hr_python_sdk.apis.paths.company_domain_v1_timetracking_record import CompanyDomainV1TimetrackingRecord
from bamboo_hr_python_sdk.apis.paths.company_domain_v1_time_tracking_timesheets_approve import CompanyDomainV1TimeTrackingTimesheetsApprove
from bamboo_hr_python_sdk.apis.paths.company_domain_v1_time_tracking_timesheets_clock_out_and_approve import CompanyDomainV1TimeTrackingTimesheetsClockOutAndApprove
from bamboo_hr_python_sdk.apis.paths.company_domain_v1_time_tracking_timesheets import CompanyDomainV1TimeTrackingTimesheets
from bamboo_hr_python_sdk.apis.paths.company_domain_v1_time_tracking_clock_in_employee_id import CompanyDomainV1TimeTrackingClockInEmployeeId
from bamboo_hr_python_sdk.apis.paths.company_domain_v1_time_tracking_clock_out_employee_id import CompanyDomainV1TimeTrackingClockOutEmployeeId
from bamboo_hr_python_sdk.apis.paths.company_domain_v1_time_tracking_daily_entries import CompanyDomainV1TimeTrackingDailyEntries
from bamboo_hr_python_sdk.apis.paths.company_domain_v1_time_tracking_clock_entries import CompanyDomainV1TimeTrackingClockEntries
from bamboo_hr_python_sdk.apis.paths.company_domain_v1_time_tracking_employee_employee_id_timesheet_timesheet_id import CompanyDomainV1TimeTrackingEmployeeEmployeeIdTimesheetTimesheetId
from bamboo_hr_python_sdk.apis.paths.company_domain_v1_time_tracking_employee_employee_id_daily_entries_id import CompanyDomainV1TimeTrackingEmployeeEmployeeIdDailyEntriesId
from bamboo_hr_python_sdk.apis.paths.company_domain_v1_time_tracking_employee_employee_id_clock_entries_id import CompanyDomainV1TimeTrackingEmployeeEmployeeIdClockEntriesId
from bamboo_hr_python_sdk.apis.paths.company_domain_v1_time_tracking_employee_employee_id_is_clocked_in import CompanyDomainV1TimeTrackingEmployeeEmployeeIdIsClockedIn
from bamboo_hr_python_sdk.apis.paths.company_domain_v1_time_tracking_employee_employee_id_clock_out_datetime import CompanyDomainV1TimeTrackingEmployeeEmployeeIdClockOutDatetime
from bamboo_hr_python_sdk.apis.paths.company_domain_v1_time_tracking_employee_employee_id_clock_in_data import CompanyDomainV1TimeTrackingEmployeeEmployeeIdClockInData
from bamboo_hr_python_sdk.apis.paths.company_domain_v1_time_tracking_employee_employee_id_projects import CompanyDomainV1TimeTrackingEmployeeEmployeeIdProjects
from bamboo_hr_python_sdk.apis.paths.company_domain_v1_time_tracking_employee_employee_id_projects_project_id_tasks import CompanyDomainV1TimeTrackingEmployeeEmployeeIdProjectsProjectIdTasks
from bamboo_hr_python_sdk.apis.paths.company_domain_v1_time_tracking_timesheet_entries import CompanyDomainV1TimeTrackingTimesheetEntries
from bamboo_hr_python_sdk.apis.paths.company_domain_v1_time_tracking_clock_entries_store import CompanyDomainV1TimeTrackingClockEntriesStore
from bamboo_hr_python_sdk.apis.paths.company_domain_v1_time_tracking_clock_entries_delete import CompanyDomainV1TimeTrackingClockEntriesDelete
from bamboo_hr_python_sdk.apis.paths.company_domain_v1_time_tracking_hour_entries_store import CompanyDomainV1TimeTrackingHourEntriesStore
from bamboo_hr_python_sdk.apis.paths.company_domain_v1_time_tracking_hour_entries_delete import CompanyDomainV1TimeTrackingHourEntriesDelete
from bamboo_hr_python_sdk.apis.paths.company_domain_v1_time_tracking_employees_employee_id_clock_in import CompanyDomainV1TimeTrackingEmployeesEmployeeIdClockIn
from bamboo_hr_python_sdk.apis.paths.company_domain_v1_time_tracking_employees_employee_id_clock_out import CompanyDomainV1TimeTrackingEmployeesEmployeeIdClockOut
from bamboo_hr_python_sdk.apis.paths.company_domain_v1_time_tracking_employees_employee_id_projects import CompanyDomainV1TimeTrackingEmployeesEmployeeIdProjects
from bamboo_hr_python_sdk.apis.paths.company_domain_v1_time_tracking_projects import CompanyDomainV1TimeTrackingProjects
from bamboo_hr_python_sdk.apis.paths.company_domain_v1_performance_employees_employee_id_goals_aggregate import CompanyDomainV1PerformanceEmployeesEmployeeIdGoalsAggregate
from bamboo_hr_python_sdk.apis.paths.company_domain_v1_1_performance_employees_employee_id_goals_aggregate import CompanyDomainV11PerformanceEmployeesEmployeeIdGoalsAggregate
from bamboo_hr_python_sdk.apis.paths.company_domain_v1_2_performance_employees_employee_id_goals_aggregate import CompanyDomainV12PerformanceEmployeesEmployeeIdGoalsAggregate
from bamboo_hr_python_sdk.apis.paths.company_domain_v1_performance_employees_employee_id_goals_goal_id_aggregate import CompanyDomainV1PerformanceEmployeesEmployeeIdGoalsGoalIdAggregate
from bamboo_hr_python_sdk.apis.paths.company_domain_v1_performance_employees_employee_id_goals_goal_id_shared_with import CompanyDomainV1PerformanceEmployeesEmployeeIdGoalsGoalIdSharedWith
from bamboo_hr_python_sdk.apis.paths.company_domain_v1_performance_employees_employee_id_goals_goal_id_progress import CompanyDomainV1PerformanceEmployeesEmployeeIdGoalsGoalIdProgress
from bamboo_hr_python_sdk.apis.paths.company_domain_v1_performance_employees_employee_id_goals_filters import CompanyDomainV1PerformanceEmployeesEmployeeIdGoalsFilters
from bamboo_hr_python_sdk.apis.paths.company_domain_v1_1_performance_employees_employee_id_goals_filters import CompanyDomainV11PerformanceEmployeesEmployeeIdGoalsFilters
from bamboo_hr_python_sdk.apis.paths.company_domain_v1_performance_employees_employee_id_goals_can_create_goals import CompanyDomainV1PerformanceEmployeesEmployeeIdGoalsCanCreateGoals
from bamboo_hr_python_sdk.apis.paths.company_domain_v1_performance_employees_employee_id_goals import CompanyDomainV1PerformanceEmployeesEmployeeIdGoals
from bamboo_hr_python_sdk.apis.paths.company_domain_v1_performance_employees_employee_id_goals_goal_id import CompanyDomainV1PerformanceEmployeesEmployeeIdGoalsGoalId
from bamboo_hr_python_sdk.apis.paths.company_domain_v1_1_performance_employees_employee_id_goals_goal_id import CompanyDomainV11PerformanceEmployeesEmployeeIdGoalsGoalId
from bamboo_hr_python_sdk.apis.paths.company_domain_v1_performance_employees_employee_id_goals_goal_id_close import CompanyDomainV1PerformanceEmployeesEmployeeIdGoalsGoalIdClose
from bamboo_hr_python_sdk.apis.paths.company_domain_v1_performance_employees_employee_id_goals_goal_id_reopen import CompanyDomainV1PerformanceEmployeesEmployeeIdGoalsGoalIdReopen
from bamboo_hr_python_sdk.apis.paths.company_domain_v1_performance_employees_employee_id_goals_share_options import CompanyDomainV1PerformanceEmployeesEmployeeIdGoalsShareOptions
from bamboo_hr_python_sdk.apis.paths.company_domain_v1_performance_employees_employee_id_goals_alignment_options import CompanyDomainV1PerformanceEmployeesEmployeeIdGoalsAlignmentOptions
from bamboo_hr_python_sdk.apis.paths.company_domain_v1_performance_employees_employee_id_goals_goal_id_comments import CompanyDomainV1PerformanceEmployeesEmployeeIdGoalsGoalIdComments
from bamboo_hr_python_sdk.apis.paths.company_domain_v1_performance_employees_employee_id_goals_goal_id_comments_comment_id import CompanyDomainV1PerformanceEmployeesEmployeeIdGoalsGoalIdCommentsCommentId
from bamboo_hr_python_sdk.apis.paths.company_domain_v1_applicant_tracking_jobs import CompanyDomainV1ApplicantTrackingJobs
from bamboo_hr_python_sdk.apis.paths.company_domain_v1_applicant_tracking_applications import CompanyDomainV1ApplicantTrackingApplications
from bamboo_hr_python_sdk.apis.paths.company_domain_v1_applicant_tracking_applications_application_id import CompanyDomainV1ApplicantTrackingApplicationsApplicationId
from bamboo_hr_python_sdk.apis.paths.company_domain_v1_applicant_tracking_applications_application_id_comments import CompanyDomainV1ApplicantTrackingApplicationsApplicationIdComments
from bamboo_hr_python_sdk.apis.paths.company_domain_v1_applicant_tracking_statuses import CompanyDomainV1ApplicantTrackingStatuses
from bamboo_hr_python_sdk.apis.paths.company_domain_v1_applicant_tracking_applications_application_id_status import CompanyDomainV1ApplicantTrackingApplicationsApplicationIdStatus
from bamboo_hr_python_sdk.apis.paths.company_domain_v1_applicant_tracking_locations import CompanyDomainV1ApplicantTrackingLocations
from bamboo_hr_python_sdk.apis.paths.company_domain_v1_applicant_tracking_hiring_leads import CompanyDomainV1ApplicantTrackingHiringLeads
from bamboo_hr_python_sdk.apis.paths.company_domain_v1_applicant_tracking_application import CompanyDomainV1ApplicantTrackingApplication
from bamboo_hr_python_sdk.apis.paths.company_domain_v1_applicant_tracking_job_opening import CompanyDomainV1ApplicantTrackingJobOpening
from bamboo_hr_python_sdk.apis.paths.company_domain_v1_training_type import CompanyDomainV1TrainingType
from bamboo_hr_python_sdk.apis.paths.company_domain_v1_training_type_training_type_id import CompanyDomainV1TrainingTypeTrainingTypeId
from bamboo_hr_python_sdk.apis.paths.company_domain_v1_training_category import CompanyDomainV1TrainingCategory
from bamboo_hr_python_sdk.apis.paths.company_domain_v1_training_category_training_category_id import CompanyDomainV1TrainingCategoryTrainingCategoryId
from bamboo_hr_python_sdk.apis.paths.company_domain_v1_training_record_employee_employee_id import CompanyDomainV1TrainingRecordEmployeeEmployeeId
from bamboo_hr_python_sdk.apis.paths.company_domain_v1_training_record_employee_training_record_id import CompanyDomainV1TrainingRecordEmployeeTrainingRecordId
from bamboo_hr_python_sdk.apis.paths.company_domain_v1_webhooks_monitor_fields import CompanyDomainV1WebhooksMonitorFields
from bamboo_hr_python_sdk.apis.paths.company_domain_v1_webhooks_id_log import CompanyDomainV1WebhooksIdLog
from bamboo_hr_python_sdk.apis.paths.company_domain_v1_employees_id import CompanyDomainV1EmployeesId
from bamboo_hr_python_sdk.apis.paths.company_domain_v1_employees import CompanyDomainV1Employees
from bamboo_hr_python_sdk.apis.paths.company_domain_v1_employees_id_files_view import CompanyDomainV1EmployeesIdFilesView
from bamboo_hr_python_sdk.apis.paths.company_domain_v1_files_view import CompanyDomainV1FilesView
from bamboo_hr_python_sdk.apis.paths.company_domain_v1_meta_fields import CompanyDomainV1MetaFields
from bamboo_hr_python_sdk.apis.paths.company_domain_v1_meta_tables import CompanyDomainV1MetaTables
from bamboo_hr_python_sdk.apis.paths.company_domain_v1_meta_lists import CompanyDomainV1MetaLists
from bamboo_hr_python_sdk.apis.paths.company_domain_v1_meta_users import CompanyDomainV1MetaUsers
from bamboo_hr_python_sdk.apis.paths.company_domain_v1_meta_time_off_types import CompanyDomainV1MetaTimeOffTypes
from bamboo_hr_python_sdk.apis.paths.company_domain_v1_meta_time_off_policies import CompanyDomainV1MetaTimeOffPolicies
from bamboo_hr_python_sdk.apis.paths.company_domain_v1_time_off_requests import CompanyDomainV1TimeOffRequests
from bamboo_hr_python_sdk.apis.paths.company_domain_v1_employees_employee_id_time_off_history import CompanyDomainV1EmployeesEmployeeIdTimeOffHistory
from bamboo_hr_python_sdk.apis.paths.company_domain_v1_employees_employee_id_time_off_balance_adjustment import CompanyDomainV1EmployeesEmployeeIdTimeOffBalanceAdjustment
from bamboo_hr_python_sdk.apis.paths.company_domain_v1_time_off_whos_out import CompanyDomainV1TimeOffWhosOut
from bamboo_hr_python_sdk.apis.paths.company_domain_v1_webhooks import CompanyDomainV1Webhooks
from bamboo_hr_python_sdk.apis.paths.company_domain_v1_webhooks_id import CompanyDomainV1WebhooksId

PathToApi = typing_extensions.TypedDict(
    'PathToApi',
    {
        PathValues.COMPANY_DOMAIN_V1_EMPLOYEES_DIRECTORY: CompanyDomainV1EmployeesDirectory,
        PathValues.COMPANY_DOMAIN_V1_EMPLOYEES_FILES_CATEGORIES: CompanyDomainV1EmployeesFilesCategories,
        PathValues.COMPANY_DOMAIN_V1_EMPLOYEES_ID_FILES_FILE_ID: CompanyDomainV1EmployeesIdFilesFileId,
        PathValues.COMPANY_DOMAIN_V1_EMPLOYEES_ID_FILES: CompanyDomainV1EmployeesIdFiles,
        PathValues.COMPANY_DOMAIN_V1_FILES_CATEGORIES: CompanyDomainV1FilesCategories,
        PathValues.COMPANY_DOMAIN_V1_FILES_FILE_ID: CompanyDomainV1FilesFileId,
        PathValues.COMPANY_DOMAIN_V1_FILES: CompanyDomainV1Files,
        PathValues.COMPANY_DOMAIN_V1_REPORTS_ID: CompanyDomainV1ReportsId,
        PathValues.COMPANY_DOMAIN_V1_REPORTS_CUSTOM: CompanyDomainV1ReportsCustom,
        PathValues.COMPANY_DOMAIN_V1_EMPLOYEES_ID_TABLES_TABLE: CompanyDomainV1EmployeesIdTablesTable,
        PathValues.COMPANY_DOMAIN_V1_EMPLOYEES_ID_TABLES_TABLE_ROW_ID: CompanyDomainV1EmployeesIdTablesTableRowId,
        PathValues.COMPANY_DOMAIN_V1_1_EMPLOYEES_ID_TABLES_TABLE_ROW_ID: CompanyDomainV11EmployeesIdTablesTableRowId,
        PathValues.COMPANY_DOMAIN_V1_1_EMPLOYEES_ID_TABLES_TABLE: CompanyDomainV11EmployeesIdTablesTable,
        PathValues.COMPANY_DOMAIN_V1_EMPLOYEES_CHANGED_TABLES_TABLE: CompanyDomainV1EmployeesChangedTablesTable,
        PathValues.COMPANY_DOMAIN_V1_META_LISTS_LIST_FIELD_ID: CompanyDomainV1MetaListsListFieldId,
        PathValues.COMPANY_DOMAIN_V1_EMPLOYEES_EMPLOYEE_ID_TIME_OFF_REQUEST: CompanyDomainV1EmployeesEmployeeIdTimeOffRequest,
        PathValues.COMPANY_DOMAIN_V1_TIME_OFF_REQUESTS_REQUEST_ID_STATUS: CompanyDomainV1TimeOffRequestsRequestIdStatus,
        PathValues.COMPANY_DOMAIN_V1_EMPLOYEES_EMPLOYEE_ID_TIME_OFF_POLICIES: CompanyDomainV1EmployeesEmployeeIdTimeOffPolicies,
        PathValues.COMPANY_DOMAIN_V1_1_EMPLOYEES_EMPLOYEE_ID_TIME_OFF_POLICIES: CompanyDomainV11EmployeesEmployeeIdTimeOffPolicies,
        PathValues.COMPANY_DOMAIN_V1_EMPLOYEES_EMPLOYEE_ID_TIME_OFF_CALCULATOR: CompanyDomainV1EmployeesEmployeeIdTimeOffCalculator,
        PathValues.COMPANY_DOMAIN_V1_EMPLOYEES_EMPLOYEE_ID_PHOTO_SIZE: CompanyDomainV1EmployeesEmployeeIdPhotoSize,
        PathValues.COMPANY_DOMAIN_V1_EMPLOYEES_EMPLOYEE_ID_PHOTO: CompanyDomainV1EmployeesEmployeeIdPhoto,
        PathValues.COMPANY_DOMAIN_V1_EMPLOYEES_CHANGED: CompanyDomainV1EmployeesChanged,
        PathValues.COMPANY_DOMAIN_V1_LOGIN: CompanyDomainV1Login,
        PathValues.COMPANY_DOMAIN_V1_BENEFITS_SETTINGS_DEDUCTION_TYPES_ALL: CompanyDomainV1BenefitsSettingsDeductionTypesAll,
        PathValues.COMPANY_DOMAIN_V1_BENEFIT_COMPANY_BENEFIT: CompanyDomainV1BenefitCompanyBenefit,
        PathValues.COMPANY_DOMAIN_V1_BENEFIT_COMPANY_BENEFIT_ID: CompanyDomainV1BenefitCompanyBenefitId,
        PathValues.COMPANY_DOMAIN_V1_BENEFIT_COMPANY_BENEFIT_TYPE: CompanyDomainV1BenefitCompanyBenefitType,
        PathValues.COMPANY_DOMAIN_V1_BENEFIT_EMPLOYEE_BENEFIT: CompanyDomainV1BenefitEmployeeBenefit,
        PathValues.COMPANY_DOMAIN_V1_BENEFITCOVERAGES: CompanyDomainV1Benefitcoverages,
        PathValues.COMPANY_DOMAIN_V1_EMPLOYEEDEPENDENTS_ID: CompanyDomainV1EmployeedependentsId,
        PathValues.COMPANY_DOMAIN_V1_EMPLOYEEDEPENDENTS: CompanyDomainV1Employeedependents,
        PathValues.COMPANY_DOMAIN_V1_BENEFITPLANS: CompanyDomainV1Benefitplans,
        PathValues.COMPANY_DOMAIN_V1_BENEFITPLANCOVERAGES: CompanyDomainV1Benefitplancoverages,
        PathValues.COMPANY_DOMAIN_V1_BENEFITGROUPS: CompanyDomainV1Benefitgroups,
        PathValues.COMPANY_DOMAIN_V1_BENEFITGROUPEMPLOYEES: CompanyDomainV1Benefitgroupemployees,
        PathValues.COMPANY_DOMAIN_V1_BENEFITGROUPPLANS: CompanyDomainV1Benefitgroupplans,
        PathValues.COMPANY_DOMAIN_V1_BENEFITGROUPPLANCOSTS: CompanyDomainV1Benefitgroupplancosts,
        PathValues.COMPANY_DOMAIN_V1_EMPLOYEE_DEDUCTIONS_ID: CompanyDomainV1EmployeeDeductionsId,
        PathValues.COMPANY_DOMAIN_V1_EMPLOYEE_PLANS_ID: CompanyDomainV1EmployeePlansId,
        PathValues.COMPANY_DOMAIN_V1_PAYROLL_DEDUCTIONS_ID: CompanyDomainV1PayrollDeductionsId,
        PathValues.COMPANY_DOMAIN_V1_EMPLOYEE_WITHHOLDING_ID: CompanyDomainV1EmployeeWithholdingId,
        PathValues.COMPANY_DOMAIN_V1_EMPLOYEE_DIRECT_DEPOSIT_ACCOUNTS_ID: CompanyDomainV1EmployeeDirectDepositAccountsId,
        PathValues.COMPANY_DOMAIN_V1_EMPLOYEE_UNPAID_PAY_STUBS_ID: CompanyDomainV1EmployeeUnpaidPayStubsId,
        PathValues.COMPANY_DOMAIN_V1_EMPLOYEE_UNPAID_PAY_STUBS: CompanyDomainV1EmployeeUnpaidPayStubs,
        PathValues.COMPANY_DOMAIN_V1_EMPLOYEE_PAY_STUB_ID: CompanyDomainV1EmployeePayStubId,
        PathValues.COMPANY_DOMAIN_V1_EMPLOYEE_PAY_STUB: CompanyDomainV1EmployeePayStub,
        PathValues.COMPANY_DOMAIN_V1_TIMETRACKING_RECORD_ID: CompanyDomainV1TimetrackingRecordId,
        PathValues.COMPANY_DOMAIN_V1_TIMETRACKING_ADD: CompanyDomainV1TimetrackingAdd,
        PathValues.COMPANY_DOMAIN_V1_TIMETRACKING_ADJUST: CompanyDomainV1TimetrackingAdjust,
        PathValues.COMPANY_DOMAIN_V1_TIMETRACKING_DELETE_ID: CompanyDomainV1TimetrackingDeleteId,
        PathValues.COMPANY_DOMAIN_V1_TIMETRACKING_RECORD: CompanyDomainV1TimetrackingRecord,
        PathValues.COMPANY_DOMAIN_V1_TIME_TRACKING_TIMESHEETS_APPROVE: CompanyDomainV1TimeTrackingTimesheetsApprove,
        PathValues.COMPANY_DOMAIN_V1_TIME_TRACKING_TIMESHEETS_CLOCK_OUT_AND_APPROVE: CompanyDomainV1TimeTrackingTimesheetsClockOutAndApprove,
        PathValues.COMPANY_DOMAIN_V1_TIME_TRACKING_TIMESHEETS: CompanyDomainV1TimeTrackingTimesheets,
        PathValues.COMPANY_DOMAIN_V1_TIME_TRACKING_CLOCK_IN_EMPLOYEE_ID: CompanyDomainV1TimeTrackingClockInEmployeeId,
        PathValues.COMPANY_DOMAIN_V1_TIME_TRACKING_CLOCK_OUT_EMPLOYEE_ID: CompanyDomainV1TimeTrackingClockOutEmployeeId,
        PathValues.COMPANY_DOMAIN_V1_TIME_TRACKING_DAILY_ENTRIES: CompanyDomainV1TimeTrackingDailyEntries,
        PathValues.COMPANY_DOMAIN_V1_TIME_TRACKING_CLOCK_ENTRIES: CompanyDomainV1TimeTrackingClockEntries,
        PathValues.COMPANY_DOMAIN_V1_TIME_TRACKING_EMPLOYEE_EMPLOYEE_ID_TIMESHEET_TIMESHEET_ID: CompanyDomainV1TimeTrackingEmployeeEmployeeIdTimesheetTimesheetId,
        PathValues.COMPANY_DOMAIN_V1_TIME_TRACKING_EMPLOYEE_EMPLOYEE_ID_DAILY_ENTRIES_ID: CompanyDomainV1TimeTrackingEmployeeEmployeeIdDailyEntriesId,
        PathValues.COMPANY_DOMAIN_V1_TIME_TRACKING_EMPLOYEE_EMPLOYEE_ID_CLOCK_ENTRIES_ID: CompanyDomainV1TimeTrackingEmployeeEmployeeIdClockEntriesId,
        PathValues.COMPANY_DOMAIN_V1_TIME_TRACKING_EMPLOYEE_EMPLOYEE_ID_IS_CLOCKED_IN: CompanyDomainV1TimeTrackingEmployeeEmployeeIdIsClockedIn,
        PathValues.COMPANY_DOMAIN_V1_TIME_TRACKING_EMPLOYEE_EMPLOYEE_ID_CLOCK_OUT_DATETIME: CompanyDomainV1TimeTrackingEmployeeEmployeeIdClockOutDatetime,
        PathValues.COMPANY_DOMAIN_V1_TIME_TRACKING_EMPLOYEE_EMPLOYEE_ID_CLOCK_IN_DATA: CompanyDomainV1TimeTrackingEmployeeEmployeeIdClockInData,
        PathValues.COMPANY_DOMAIN_V1_TIME_TRACKING_EMPLOYEE_EMPLOYEE_ID_PROJECTS: CompanyDomainV1TimeTrackingEmployeeEmployeeIdProjects,
        PathValues.COMPANY_DOMAIN_V1_TIME_TRACKING_EMPLOYEE_EMPLOYEE_ID_PROJECTS_PROJECT_ID_TASKS: CompanyDomainV1TimeTrackingEmployeeEmployeeIdProjectsProjectIdTasks,
        PathValues.COMPANY_DOMAIN_V1_TIME_TRACKING_TIMESHEET_ENTRIES: CompanyDomainV1TimeTrackingTimesheetEntries,
        PathValues.COMPANY_DOMAIN_V1_TIME_TRACKING_CLOCK_ENTRIES_STORE: CompanyDomainV1TimeTrackingClockEntriesStore,
        PathValues.COMPANY_DOMAIN_V1_TIME_TRACKING_CLOCK_ENTRIES_DELETE: CompanyDomainV1TimeTrackingClockEntriesDelete,
        PathValues.COMPANY_DOMAIN_V1_TIME_TRACKING_HOUR_ENTRIES_STORE: CompanyDomainV1TimeTrackingHourEntriesStore,
        PathValues.COMPANY_DOMAIN_V1_TIME_TRACKING_HOUR_ENTRIES_DELETE: CompanyDomainV1TimeTrackingHourEntriesDelete,
        PathValues.COMPANY_DOMAIN_V1_TIME_TRACKING_EMPLOYEES_EMPLOYEE_ID_CLOCK_IN: CompanyDomainV1TimeTrackingEmployeesEmployeeIdClockIn,
        PathValues.COMPANY_DOMAIN_V1_TIME_TRACKING_EMPLOYEES_EMPLOYEE_ID_CLOCK_OUT: CompanyDomainV1TimeTrackingEmployeesEmployeeIdClockOut,
        PathValues.COMPANY_DOMAIN_V1_TIME_TRACKING_EMPLOYEES_EMPLOYEE_ID_PROJECTS: CompanyDomainV1TimeTrackingEmployeesEmployeeIdProjects,
        PathValues.COMPANY_DOMAIN_V1_TIME_TRACKING_PROJECTS: CompanyDomainV1TimeTrackingProjects,
        PathValues.COMPANY_DOMAIN_V1_PERFORMANCE_EMPLOYEES_EMPLOYEE_ID_GOALS_AGGREGATE: CompanyDomainV1PerformanceEmployeesEmployeeIdGoalsAggregate,
        PathValues.COMPANY_DOMAIN_V1_1_PERFORMANCE_EMPLOYEES_EMPLOYEE_ID_GOALS_AGGREGATE: CompanyDomainV11PerformanceEmployeesEmployeeIdGoalsAggregate,
        PathValues.COMPANY_DOMAIN_V1_2_PERFORMANCE_EMPLOYEES_EMPLOYEE_ID_GOALS_AGGREGATE: CompanyDomainV12PerformanceEmployeesEmployeeIdGoalsAggregate,
        PathValues.COMPANY_DOMAIN_V1_PERFORMANCE_EMPLOYEES_EMPLOYEE_ID_GOALS_GOAL_ID_AGGREGATE: CompanyDomainV1PerformanceEmployeesEmployeeIdGoalsGoalIdAggregate,
        PathValues.COMPANY_DOMAIN_V1_PERFORMANCE_EMPLOYEES_EMPLOYEE_ID_GOALS_GOAL_ID_SHARED_WITH: CompanyDomainV1PerformanceEmployeesEmployeeIdGoalsGoalIdSharedWith,
        PathValues.COMPANY_DOMAIN_V1_PERFORMANCE_EMPLOYEES_EMPLOYEE_ID_GOALS_GOAL_ID_PROGRESS: CompanyDomainV1PerformanceEmployeesEmployeeIdGoalsGoalIdProgress,
        PathValues.COMPANY_DOMAIN_V1_PERFORMANCE_EMPLOYEES_EMPLOYEE_ID_GOALS_FILTERS: CompanyDomainV1PerformanceEmployeesEmployeeIdGoalsFilters,
        PathValues.COMPANY_DOMAIN_V1_1_PERFORMANCE_EMPLOYEES_EMPLOYEE_ID_GOALS_FILTERS: CompanyDomainV11PerformanceEmployeesEmployeeIdGoalsFilters,
        PathValues.COMPANY_DOMAIN_V1_PERFORMANCE_EMPLOYEES_EMPLOYEE_ID_GOALS_CAN_CREATE_GOALS: CompanyDomainV1PerformanceEmployeesEmployeeIdGoalsCanCreateGoals,
        PathValues.COMPANY_DOMAIN_V1_PERFORMANCE_EMPLOYEES_EMPLOYEE_ID_GOALS: CompanyDomainV1PerformanceEmployeesEmployeeIdGoals,
        PathValues.COMPANY_DOMAIN_V1_PERFORMANCE_EMPLOYEES_EMPLOYEE_ID_GOALS_GOAL_ID: CompanyDomainV1PerformanceEmployeesEmployeeIdGoalsGoalId,
        PathValues.COMPANY_DOMAIN_V1_1_PERFORMANCE_EMPLOYEES_EMPLOYEE_ID_GOALS_GOAL_ID: CompanyDomainV11PerformanceEmployeesEmployeeIdGoalsGoalId,
        PathValues.COMPANY_DOMAIN_V1_PERFORMANCE_EMPLOYEES_EMPLOYEE_ID_GOALS_GOAL_ID_CLOSE: CompanyDomainV1PerformanceEmployeesEmployeeIdGoalsGoalIdClose,
        PathValues.COMPANY_DOMAIN_V1_PERFORMANCE_EMPLOYEES_EMPLOYEE_ID_GOALS_GOAL_ID_REOPEN: CompanyDomainV1PerformanceEmployeesEmployeeIdGoalsGoalIdReopen,
        PathValues.COMPANY_DOMAIN_V1_PERFORMANCE_EMPLOYEES_EMPLOYEE_ID_GOALS_SHARE_OPTIONS: CompanyDomainV1PerformanceEmployeesEmployeeIdGoalsShareOptions,
        PathValues.COMPANY_DOMAIN_V1_PERFORMANCE_EMPLOYEES_EMPLOYEE_ID_GOALS_ALIGNMENT_OPTIONS: CompanyDomainV1PerformanceEmployeesEmployeeIdGoalsAlignmentOptions,
        PathValues.COMPANY_DOMAIN_V1_PERFORMANCE_EMPLOYEES_EMPLOYEE_ID_GOALS_GOAL_ID_COMMENTS: CompanyDomainV1PerformanceEmployeesEmployeeIdGoalsGoalIdComments,
        PathValues.COMPANY_DOMAIN_V1_PERFORMANCE_EMPLOYEES_EMPLOYEE_ID_GOALS_GOAL_ID_COMMENTS_COMMENT_ID: CompanyDomainV1PerformanceEmployeesEmployeeIdGoalsGoalIdCommentsCommentId,
        PathValues.COMPANY_DOMAIN_V1_APPLICANT_TRACKING_JOBS: CompanyDomainV1ApplicantTrackingJobs,
        PathValues.COMPANY_DOMAIN_V1_APPLICANT_TRACKING_APPLICATIONS: CompanyDomainV1ApplicantTrackingApplications,
        PathValues.COMPANY_DOMAIN_V1_APPLICANT_TRACKING_APPLICATIONS_APPLICATION_ID: CompanyDomainV1ApplicantTrackingApplicationsApplicationId,
        PathValues.COMPANY_DOMAIN_V1_APPLICANT_TRACKING_APPLICATIONS_APPLICATION_ID_COMMENTS: CompanyDomainV1ApplicantTrackingApplicationsApplicationIdComments,
        PathValues.COMPANY_DOMAIN_V1_APPLICANT_TRACKING_STATUSES: CompanyDomainV1ApplicantTrackingStatuses,
        PathValues.COMPANY_DOMAIN_V1_APPLICANT_TRACKING_APPLICATIONS_APPLICATION_ID_STATUS: CompanyDomainV1ApplicantTrackingApplicationsApplicationIdStatus,
        PathValues.COMPANY_DOMAIN_V1_APPLICANT_TRACKING_LOCATIONS: CompanyDomainV1ApplicantTrackingLocations,
        PathValues.COMPANY_DOMAIN_V1_APPLICANT_TRACKING_HIRING_LEADS: CompanyDomainV1ApplicantTrackingHiringLeads,
        PathValues.COMPANY_DOMAIN_V1_APPLICANT_TRACKING_APPLICATION: CompanyDomainV1ApplicantTrackingApplication,
        PathValues.COMPANY_DOMAIN_V1_APPLICANT_TRACKING_JOB_OPENING: CompanyDomainV1ApplicantTrackingJobOpening,
        PathValues.COMPANY_DOMAIN_V1_TRAINING_TYPE: CompanyDomainV1TrainingType,
        PathValues.COMPANY_DOMAIN_V1_TRAINING_TYPE_TRAINING_TYPE_ID: CompanyDomainV1TrainingTypeTrainingTypeId,
        PathValues.COMPANY_DOMAIN_V1_TRAINING_CATEGORY: CompanyDomainV1TrainingCategory,
        PathValues.COMPANY_DOMAIN_V1_TRAINING_CATEGORY_TRAINING_CATEGORY_ID: CompanyDomainV1TrainingCategoryTrainingCategoryId,
        PathValues.COMPANY_DOMAIN_V1_TRAINING_RECORD_EMPLOYEE_EMPLOYEE_ID: CompanyDomainV1TrainingRecordEmployeeEmployeeId,
        PathValues.COMPANY_DOMAIN_V1_TRAINING_RECORD_EMPLOYEE_TRAINING_RECORD_ID: CompanyDomainV1TrainingRecordEmployeeTrainingRecordId,
        PathValues.COMPANY_DOMAIN_V1_WEBHOOKS_MONITOR_FIELDS: CompanyDomainV1WebhooksMonitorFields,
        PathValues.COMPANY_DOMAIN_V1_WEBHOOKS_ID_LOG: CompanyDomainV1WebhooksIdLog,
        PathValues.COMPANY_DOMAIN_V1_EMPLOYEES_ID: CompanyDomainV1EmployeesId,
        PathValues.COMPANY_DOMAIN_V1_EMPLOYEES: CompanyDomainV1Employees,
        PathValues.COMPANY_DOMAIN_V1_EMPLOYEES_ID_FILES_VIEW: CompanyDomainV1EmployeesIdFilesView,
        PathValues.COMPANY_DOMAIN_V1_FILES_VIEW: CompanyDomainV1FilesView,
        PathValues.COMPANY_DOMAIN_V1_META_FIELDS: CompanyDomainV1MetaFields,
        PathValues.COMPANY_DOMAIN_V1_META_TABLES: CompanyDomainV1MetaTables,
        PathValues.COMPANY_DOMAIN_V1_META_LISTS: CompanyDomainV1MetaLists,
        PathValues.COMPANY_DOMAIN_V1_META_USERS: CompanyDomainV1MetaUsers,
        PathValues.COMPANY_DOMAIN_V1_META_TIME_OFF_TYPES: CompanyDomainV1MetaTimeOffTypes,
        PathValues.COMPANY_DOMAIN_V1_META_TIME_OFF_POLICIES: CompanyDomainV1MetaTimeOffPolicies,
        PathValues.COMPANY_DOMAIN_V1_TIME_OFF_REQUESTS: CompanyDomainV1TimeOffRequests,
        PathValues.COMPANY_DOMAIN_V1_EMPLOYEES_EMPLOYEE_ID_TIME_OFF_HISTORY: CompanyDomainV1EmployeesEmployeeIdTimeOffHistory,
        PathValues.COMPANY_DOMAIN_V1_EMPLOYEES_EMPLOYEE_ID_TIME_OFF_BALANCE_ADJUSTMENT: CompanyDomainV1EmployeesEmployeeIdTimeOffBalanceAdjustment,
        PathValues.COMPANY_DOMAIN_V1_TIME_OFF_WHOS_OUT: CompanyDomainV1TimeOffWhosOut,
        PathValues.COMPANY_DOMAIN_V1_WEBHOOKS: CompanyDomainV1Webhooks,
        PathValues.COMPANY_DOMAIN_V1_WEBHOOKS_ID: CompanyDomainV1WebhooksId,
    }
)

path_to_api = PathToApi(
    {
        PathValues.COMPANY_DOMAIN_V1_EMPLOYEES_DIRECTORY: CompanyDomainV1EmployeesDirectory,
        PathValues.COMPANY_DOMAIN_V1_EMPLOYEES_FILES_CATEGORIES: CompanyDomainV1EmployeesFilesCategories,
        PathValues.COMPANY_DOMAIN_V1_EMPLOYEES_ID_FILES_FILE_ID: CompanyDomainV1EmployeesIdFilesFileId,
        PathValues.COMPANY_DOMAIN_V1_EMPLOYEES_ID_FILES: CompanyDomainV1EmployeesIdFiles,
        PathValues.COMPANY_DOMAIN_V1_FILES_CATEGORIES: CompanyDomainV1FilesCategories,
        PathValues.COMPANY_DOMAIN_V1_FILES_FILE_ID: CompanyDomainV1FilesFileId,
        PathValues.COMPANY_DOMAIN_V1_FILES: CompanyDomainV1Files,
        PathValues.COMPANY_DOMAIN_V1_REPORTS_ID: CompanyDomainV1ReportsId,
        PathValues.COMPANY_DOMAIN_V1_REPORTS_CUSTOM: CompanyDomainV1ReportsCustom,
        PathValues.COMPANY_DOMAIN_V1_EMPLOYEES_ID_TABLES_TABLE: CompanyDomainV1EmployeesIdTablesTable,
        PathValues.COMPANY_DOMAIN_V1_EMPLOYEES_ID_TABLES_TABLE_ROW_ID: CompanyDomainV1EmployeesIdTablesTableRowId,
        PathValues.COMPANY_DOMAIN_V1_1_EMPLOYEES_ID_TABLES_TABLE_ROW_ID: CompanyDomainV11EmployeesIdTablesTableRowId,
        PathValues.COMPANY_DOMAIN_V1_1_EMPLOYEES_ID_TABLES_TABLE: CompanyDomainV11EmployeesIdTablesTable,
        PathValues.COMPANY_DOMAIN_V1_EMPLOYEES_CHANGED_TABLES_TABLE: CompanyDomainV1EmployeesChangedTablesTable,
        PathValues.COMPANY_DOMAIN_V1_META_LISTS_LIST_FIELD_ID: CompanyDomainV1MetaListsListFieldId,
        PathValues.COMPANY_DOMAIN_V1_EMPLOYEES_EMPLOYEE_ID_TIME_OFF_REQUEST: CompanyDomainV1EmployeesEmployeeIdTimeOffRequest,
        PathValues.COMPANY_DOMAIN_V1_TIME_OFF_REQUESTS_REQUEST_ID_STATUS: CompanyDomainV1TimeOffRequestsRequestIdStatus,
        PathValues.COMPANY_DOMAIN_V1_EMPLOYEES_EMPLOYEE_ID_TIME_OFF_POLICIES: CompanyDomainV1EmployeesEmployeeIdTimeOffPolicies,
        PathValues.COMPANY_DOMAIN_V1_1_EMPLOYEES_EMPLOYEE_ID_TIME_OFF_POLICIES: CompanyDomainV11EmployeesEmployeeIdTimeOffPolicies,
        PathValues.COMPANY_DOMAIN_V1_EMPLOYEES_EMPLOYEE_ID_TIME_OFF_CALCULATOR: CompanyDomainV1EmployeesEmployeeIdTimeOffCalculator,
        PathValues.COMPANY_DOMAIN_V1_EMPLOYEES_EMPLOYEE_ID_PHOTO_SIZE: CompanyDomainV1EmployeesEmployeeIdPhotoSize,
        PathValues.COMPANY_DOMAIN_V1_EMPLOYEES_EMPLOYEE_ID_PHOTO: CompanyDomainV1EmployeesEmployeeIdPhoto,
        PathValues.COMPANY_DOMAIN_V1_EMPLOYEES_CHANGED: CompanyDomainV1EmployeesChanged,
        PathValues.COMPANY_DOMAIN_V1_LOGIN: CompanyDomainV1Login,
        PathValues.COMPANY_DOMAIN_V1_BENEFITS_SETTINGS_DEDUCTION_TYPES_ALL: CompanyDomainV1BenefitsSettingsDeductionTypesAll,
        PathValues.COMPANY_DOMAIN_V1_BENEFIT_COMPANY_BENEFIT: CompanyDomainV1BenefitCompanyBenefit,
        PathValues.COMPANY_DOMAIN_V1_BENEFIT_COMPANY_BENEFIT_ID: CompanyDomainV1BenefitCompanyBenefitId,
        PathValues.COMPANY_DOMAIN_V1_BENEFIT_COMPANY_BENEFIT_TYPE: CompanyDomainV1BenefitCompanyBenefitType,
        PathValues.COMPANY_DOMAIN_V1_BENEFIT_EMPLOYEE_BENEFIT: CompanyDomainV1BenefitEmployeeBenefit,
        PathValues.COMPANY_DOMAIN_V1_BENEFITCOVERAGES: CompanyDomainV1Benefitcoverages,
        PathValues.COMPANY_DOMAIN_V1_EMPLOYEEDEPENDENTS_ID: CompanyDomainV1EmployeedependentsId,
        PathValues.COMPANY_DOMAIN_V1_EMPLOYEEDEPENDENTS: CompanyDomainV1Employeedependents,
        PathValues.COMPANY_DOMAIN_V1_BENEFITPLANS: CompanyDomainV1Benefitplans,
        PathValues.COMPANY_DOMAIN_V1_BENEFITPLANCOVERAGES: CompanyDomainV1Benefitplancoverages,
        PathValues.COMPANY_DOMAIN_V1_BENEFITGROUPS: CompanyDomainV1Benefitgroups,
        PathValues.COMPANY_DOMAIN_V1_BENEFITGROUPEMPLOYEES: CompanyDomainV1Benefitgroupemployees,
        PathValues.COMPANY_DOMAIN_V1_BENEFITGROUPPLANS: CompanyDomainV1Benefitgroupplans,
        PathValues.COMPANY_DOMAIN_V1_BENEFITGROUPPLANCOSTS: CompanyDomainV1Benefitgroupplancosts,
        PathValues.COMPANY_DOMAIN_V1_EMPLOYEE_DEDUCTIONS_ID: CompanyDomainV1EmployeeDeductionsId,
        PathValues.COMPANY_DOMAIN_V1_EMPLOYEE_PLANS_ID: CompanyDomainV1EmployeePlansId,
        PathValues.COMPANY_DOMAIN_V1_PAYROLL_DEDUCTIONS_ID: CompanyDomainV1PayrollDeductionsId,
        PathValues.COMPANY_DOMAIN_V1_EMPLOYEE_WITHHOLDING_ID: CompanyDomainV1EmployeeWithholdingId,
        PathValues.COMPANY_DOMAIN_V1_EMPLOYEE_DIRECT_DEPOSIT_ACCOUNTS_ID: CompanyDomainV1EmployeeDirectDepositAccountsId,
        PathValues.COMPANY_DOMAIN_V1_EMPLOYEE_UNPAID_PAY_STUBS_ID: CompanyDomainV1EmployeeUnpaidPayStubsId,
        PathValues.COMPANY_DOMAIN_V1_EMPLOYEE_UNPAID_PAY_STUBS: CompanyDomainV1EmployeeUnpaidPayStubs,
        PathValues.COMPANY_DOMAIN_V1_EMPLOYEE_PAY_STUB_ID: CompanyDomainV1EmployeePayStubId,
        PathValues.COMPANY_DOMAIN_V1_EMPLOYEE_PAY_STUB: CompanyDomainV1EmployeePayStub,
        PathValues.COMPANY_DOMAIN_V1_TIMETRACKING_RECORD_ID: CompanyDomainV1TimetrackingRecordId,
        PathValues.COMPANY_DOMAIN_V1_TIMETRACKING_ADD: CompanyDomainV1TimetrackingAdd,
        PathValues.COMPANY_DOMAIN_V1_TIMETRACKING_ADJUST: CompanyDomainV1TimetrackingAdjust,
        PathValues.COMPANY_DOMAIN_V1_TIMETRACKING_DELETE_ID: CompanyDomainV1TimetrackingDeleteId,
        PathValues.COMPANY_DOMAIN_V1_TIMETRACKING_RECORD: CompanyDomainV1TimetrackingRecord,
        PathValues.COMPANY_DOMAIN_V1_TIME_TRACKING_TIMESHEETS_APPROVE: CompanyDomainV1TimeTrackingTimesheetsApprove,
        PathValues.COMPANY_DOMAIN_V1_TIME_TRACKING_TIMESHEETS_CLOCK_OUT_AND_APPROVE: CompanyDomainV1TimeTrackingTimesheetsClockOutAndApprove,
        PathValues.COMPANY_DOMAIN_V1_TIME_TRACKING_TIMESHEETS: CompanyDomainV1TimeTrackingTimesheets,
        PathValues.COMPANY_DOMAIN_V1_TIME_TRACKING_CLOCK_IN_EMPLOYEE_ID: CompanyDomainV1TimeTrackingClockInEmployeeId,
        PathValues.COMPANY_DOMAIN_V1_TIME_TRACKING_CLOCK_OUT_EMPLOYEE_ID: CompanyDomainV1TimeTrackingClockOutEmployeeId,
        PathValues.COMPANY_DOMAIN_V1_TIME_TRACKING_DAILY_ENTRIES: CompanyDomainV1TimeTrackingDailyEntries,
        PathValues.COMPANY_DOMAIN_V1_TIME_TRACKING_CLOCK_ENTRIES: CompanyDomainV1TimeTrackingClockEntries,
        PathValues.COMPANY_DOMAIN_V1_TIME_TRACKING_EMPLOYEE_EMPLOYEE_ID_TIMESHEET_TIMESHEET_ID: CompanyDomainV1TimeTrackingEmployeeEmployeeIdTimesheetTimesheetId,
        PathValues.COMPANY_DOMAIN_V1_TIME_TRACKING_EMPLOYEE_EMPLOYEE_ID_DAILY_ENTRIES_ID: CompanyDomainV1TimeTrackingEmployeeEmployeeIdDailyEntriesId,
        PathValues.COMPANY_DOMAIN_V1_TIME_TRACKING_EMPLOYEE_EMPLOYEE_ID_CLOCK_ENTRIES_ID: CompanyDomainV1TimeTrackingEmployeeEmployeeIdClockEntriesId,
        PathValues.COMPANY_DOMAIN_V1_TIME_TRACKING_EMPLOYEE_EMPLOYEE_ID_IS_CLOCKED_IN: CompanyDomainV1TimeTrackingEmployeeEmployeeIdIsClockedIn,
        PathValues.COMPANY_DOMAIN_V1_TIME_TRACKING_EMPLOYEE_EMPLOYEE_ID_CLOCK_OUT_DATETIME: CompanyDomainV1TimeTrackingEmployeeEmployeeIdClockOutDatetime,
        PathValues.COMPANY_DOMAIN_V1_TIME_TRACKING_EMPLOYEE_EMPLOYEE_ID_CLOCK_IN_DATA: CompanyDomainV1TimeTrackingEmployeeEmployeeIdClockInData,
        PathValues.COMPANY_DOMAIN_V1_TIME_TRACKING_EMPLOYEE_EMPLOYEE_ID_PROJECTS: CompanyDomainV1TimeTrackingEmployeeEmployeeIdProjects,
        PathValues.COMPANY_DOMAIN_V1_TIME_TRACKING_EMPLOYEE_EMPLOYEE_ID_PROJECTS_PROJECT_ID_TASKS: CompanyDomainV1TimeTrackingEmployeeEmployeeIdProjectsProjectIdTasks,
        PathValues.COMPANY_DOMAIN_V1_TIME_TRACKING_TIMESHEET_ENTRIES: CompanyDomainV1TimeTrackingTimesheetEntries,
        PathValues.COMPANY_DOMAIN_V1_TIME_TRACKING_CLOCK_ENTRIES_STORE: CompanyDomainV1TimeTrackingClockEntriesStore,
        PathValues.COMPANY_DOMAIN_V1_TIME_TRACKING_CLOCK_ENTRIES_DELETE: CompanyDomainV1TimeTrackingClockEntriesDelete,
        PathValues.COMPANY_DOMAIN_V1_TIME_TRACKING_HOUR_ENTRIES_STORE: CompanyDomainV1TimeTrackingHourEntriesStore,
        PathValues.COMPANY_DOMAIN_V1_TIME_TRACKING_HOUR_ENTRIES_DELETE: CompanyDomainV1TimeTrackingHourEntriesDelete,
        PathValues.COMPANY_DOMAIN_V1_TIME_TRACKING_EMPLOYEES_EMPLOYEE_ID_CLOCK_IN: CompanyDomainV1TimeTrackingEmployeesEmployeeIdClockIn,
        PathValues.COMPANY_DOMAIN_V1_TIME_TRACKING_EMPLOYEES_EMPLOYEE_ID_CLOCK_OUT: CompanyDomainV1TimeTrackingEmployeesEmployeeIdClockOut,
        PathValues.COMPANY_DOMAIN_V1_TIME_TRACKING_EMPLOYEES_EMPLOYEE_ID_PROJECTS: CompanyDomainV1TimeTrackingEmployeesEmployeeIdProjects,
        PathValues.COMPANY_DOMAIN_V1_TIME_TRACKING_PROJECTS: CompanyDomainV1TimeTrackingProjects,
        PathValues.COMPANY_DOMAIN_V1_PERFORMANCE_EMPLOYEES_EMPLOYEE_ID_GOALS_AGGREGATE: CompanyDomainV1PerformanceEmployeesEmployeeIdGoalsAggregate,
        PathValues.COMPANY_DOMAIN_V1_1_PERFORMANCE_EMPLOYEES_EMPLOYEE_ID_GOALS_AGGREGATE: CompanyDomainV11PerformanceEmployeesEmployeeIdGoalsAggregate,
        PathValues.COMPANY_DOMAIN_V1_2_PERFORMANCE_EMPLOYEES_EMPLOYEE_ID_GOALS_AGGREGATE: CompanyDomainV12PerformanceEmployeesEmployeeIdGoalsAggregate,
        PathValues.COMPANY_DOMAIN_V1_PERFORMANCE_EMPLOYEES_EMPLOYEE_ID_GOALS_GOAL_ID_AGGREGATE: CompanyDomainV1PerformanceEmployeesEmployeeIdGoalsGoalIdAggregate,
        PathValues.COMPANY_DOMAIN_V1_PERFORMANCE_EMPLOYEES_EMPLOYEE_ID_GOALS_GOAL_ID_SHARED_WITH: CompanyDomainV1PerformanceEmployeesEmployeeIdGoalsGoalIdSharedWith,
        PathValues.COMPANY_DOMAIN_V1_PERFORMANCE_EMPLOYEES_EMPLOYEE_ID_GOALS_GOAL_ID_PROGRESS: CompanyDomainV1PerformanceEmployeesEmployeeIdGoalsGoalIdProgress,
        PathValues.COMPANY_DOMAIN_V1_PERFORMANCE_EMPLOYEES_EMPLOYEE_ID_GOALS_FILTERS: CompanyDomainV1PerformanceEmployeesEmployeeIdGoalsFilters,
        PathValues.COMPANY_DOMAIN_V1_1_PERFORMANCE_EMPLOYEES_EMPLOYEE_ID_GOALS_FILTERS: CompanyDomainV11PerformanceEmployeesEmployeeIdGoalsFilters,
        PathValues.COMPANY_DOMAIN_V1_PERFORMANCE_EMPLOYEES_EMPLOYEE_ID_GOALS_CAN_CREATE_GOALS: CompanyDomainV1PerformanceEmployeesEmployeeIdGoalsCanCreateGoals,
        PathValues.COMPANY_DOMAIN_V1_PERFORMANCE_EMPLOYEES_EMPLOYEE_ID_GOALS: CompanyDomainV1PerformanceEmployeesEmployeeIdGoals,
        PathValues.COMPANY_DOMAIN_V1_PERFORMANCE_EMPLOYEES_EMPLOYEE_ID_GOALS_GOAL_ID: CompanyDomainV1PerformanceEmployeesEmployeeIdGoalsGoalId,
        PathValues.COMPANY_DOMAIN_V1_1_PERFORMANCE_EMPLOYEES_EMPLOYEE_ID_GOALS_GOAL_ID: CompanyDomainV11PerformanceEmployeesEmployeeIdGoalsGoalId,
        PathValues.COMPANY_DOMAIN_V1_PERFORMANCE_EMPLOYEES_EMPLOYEE_ID_GOALS_GOAL_ID_CLOSE: CompanyDomainV1PerformanceEmployeesEmployeeIdGoalsGoalIdClose,
        PathValues.COMPANY_DOMAIN_V1_PERFORMANCE_EMPLOYEES_EMPLOYEE_ID_GOALS_GOAL_ID_REOPEN: CompanyDomainV1PerformanceEmployeesEmployeeIdGoalsGoalIdReopen,
        PathValues.COMPANY_DOMAIN_V1_PERFORMANCE_EMPLOYEES_EMPLOYEE_ID_GOALS_SHARE_OPTIONS: CompanyDomainV1PerformanceEmployeesEmployeeIdGoalsShareOptions,
        PathValues.COMPANY_DOMAIN_V1_PERFORMANCE_EMPLOYEES_EMPLOYEE_ID_GOALS_ALIGNMENT_OPTIONS: CompanyDomainV1PerformanceEmployeesEmployeeIdGoalsAlignmentOptions,
        PathValues.COMPANY_DOMAIN_V1_PERFORMANCE_EMPLOYEES_EMPLOYEE_ID_GOALS_GOAL_ID_COMMENTS: CompanyDomainV1PerformanceEmployeesEmployeeIdGoalsGoalIdComments,
        PathValues.COMPANY_DOMAIN_V1_PERFORMANCE_EMPLOYEES_EMPLOYEE_ID_GOALS_GOAL_ID_COMMENTS_COMMENT_ID: CompanyDomainV1PerformanceEmployeesEmployeeIdGoalsGoalIdCommentsCommentId,
        PathValues.COMPANY_DOMAIN_V1_APPLICANT_TRACKING_JOBS: CompanyDomainV1ApplicantTrackingJobs,
        PathValues.COMPANY_DOMAIN_V1_APPLICANT_TRACKING_APPLICATIONS: CompanyDomainV1ApplicantTrackingApplications,
        PathValues.COMPANY_DOMAIN_V1_APPLICANT_TRACKING_APPLICATIONS_APPLICATION_ID: CompanyDomainV1ApplicantTrackingApplicationsApplicationId,
        PathValues.COMPANY_DOMAIN_V1_APPLICANT_TRACKING_APPLICATIONS_APPLICATION_ID_COMMENTS: CompanyDomainV1ApplicantTrackingApplicationsApplicationIdComments,
        PathValues.COMPANY_DOMAIN_V1_APPLICANT_TRACKING_STATUSES: CompanyDomainV1ApplicantTrackingStatuses,
        PathValues.COMPANY_DOMAIN_V1_APPLICANT_TRACKING_APPLICATIONS_APPLICATION_ID_STATUS: CompanyDomainV1ApplicantTrackingApplicationsApplicationIdStatus,
        PathValues.COMPANY_DOMAIN_V1_APPLICANT_TRACKING_LOCATIONS: CompanyDomainV1ApplicantTrackingLocations,
        PathValues.COMPANY_DOMAIN_V1_APPLICANT_TRACKING_HIRING_LEADS: CompanyDomainV1ApplicantTrackingHiringLeads,
        PathValues.COMPANY_DOMAIN_V1_APPLICANT_TRACKING_APPLICATION: CompanyDomainV1ApplicantTrackingApplication,
        PathValues.COMPANY_DOMAIN_V1_APPLICANT_TRACKING_JOB_OPENING: CompanyDomainV1ApplicantTrackingJobOpening,
        PathValues.COMPANY_DOMAIN_V1_TRAINING_TYPE: CompanyDomainV1TrainingType,
        PathValues.COMPANY_DOMAIN_V1_TRAINING_TYPE_TRAINING_TYPE_ID: CompanyDomainV1TrainingTypeTrainingTypeId,
        PathValues.COMPANY_DOMAIN_V1_TRAINING_CATEGORY: CompanyDomainV1TrainingCategory,
        PathValues.COMPANY_DOMAIN_V1_TRAINING_CATEGORY_TRAINING_CATEGORY_ID: CompanyDomainV1TrainingCategoryTrainingCategoryId,
        PathValues.COMPANY_DOMAIN_V1_TRAINING_RECORD_EMPLOYEE_EMPLOYEE_ID: CompanyDomainV1TrainingRecordEmployeeEmployeeId,
        PathValues.COMPANY_DOMAIN_V1_TRAINING_RECORD_EMPLOYEE_TRAINING_RECORD_ID: CompanyDomainV1TrainingRecordEmployeeTrainingRecordId,
        PathValues.COMPANY_DOMAIN_V1_WEBHOOKS_MONITOR_FIELDS: CompanyDomainV1WebhooksMonitorFields,
        PathValues.COMPANY_DOMAIN_V1_WEBHOOKS_ID_LOG: CompanyDomainV1WebhooksIdLog,
        PathValues.COMPANY_DOMAIN_V1_EMPLOYEES_ID: CompanyDomainV1EmployeesId,
        PathValues.COMPANY_DOMAIN_V1_EMPLOYEES: CompanyDomainV1Employees,
        PathValues.COMPANY_DOMAIN_V1_EMPLOYEES_ID_FILES_VIEW: CompanyDomainV1EmployeesIdFilesView,
        PathValues.COMPANY_DOMAIN_V1_FILES_VIEW: CompanyDomainV1FilesView,
        PathValues.COMPANY_DOMAIN_V1_META_FIELDS: CompanyDomainV1MetaFields,
        PathValues.COMPANY_DOMAIN_V1_META_TABLES: CompanyDomainV1MetaTables,
        PathValues.COMPANY_DOMAIN_V1_META_LISTS: CompanyDomainV1MetaLists,
        PathValues.COMPANY_DOMAIN_V1_META_USERS: CompanyDomainV1MetaUsers,
        PathValues.COMPANY_DOMAIN_V1_META_TIME_OFF_TYPES: CompanyDomainV1MetaTimeOffTypes,
        PathValues.COMPANY_DOMAIN_V1_META_TIME_OFF_POLICIES: CompanyDomainV1MetaTimeOffPolicies,
        PathValues.COMPANY_DOMAIN_V1_TIME_OFF_REQUESTS: CompanyDomainV1TimeOffRequests,
        PathValues.COMPANY_DOMAIN_V1_EMPLOYEES_EMPLOYEE_ID_TIME_OFF_HISTORY: CompanyDomainV1EmployeesEmployeeIdTimeOffHistory,
        PathValues.COMPANY_DOMAIN_V1_EMPLOYEES_EMPLOYEE_ID_TIME_OFF_BALANCE_ADJUSTMENT: CompanyDomainV1EmployeesEmployeeIdTimeOffBalanceAdjustment,
        PathValues.COMPANY_DOMAIN_V1_TIME_OFF_WHOS_OUT: CompanyDomainV1TimeOffWhosOut,
        PathValues.COMPANY_DOMAIN_V1_WEBHOOKS: CompanyDomainV1Webhooks,
        PathValues.COMPANY_DOMAIN_V1_WEBHOOKS_ID: CompanyDomainV1WebhooksId,
    }
)
