# coding: utf-8

"""
    BambooHR API

    This is the majority of the API requests including some that are not documented.  http://www.bamboohr.com/api/documentation/

    The version of the OpenAPI document: v1
    Generated by: https://konfigthis.com
"""

import unittest

import bamboo_hr_python_sdk
from bamboo_hr_python_sdk.model.goals_get_all_aggregate_info_response_persons_item import GoalsGetAllAggregateInfoResponsePersonsItem
from bamboo_hr_python_sdk import configuration


class TestGoalsGetAllAggregateInfoResponsePersonsItem(unittest.TestCase):
    """GoalsGetAllAggregateInfoResponsePersonsItem unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
