# coding: utf-8

"""
    BambooHR API

    This is the majority of the API requests including some that are not documented.  http://www.bamboohr.com/api/documentation/

    The version of the OpenAPI document: v1
    Generated by: https://konfigthis.com
"""

import unittest

import bamboo_hr_python_sdk
from bamboo_hr_python_sdk.model.update_goal_v11 import UpdateGoalV11
from bamboo_hr_python_sdk import configuration


class TestUpdateGoalV11(unittest.TestCase):
    """UpdateGoalV11 unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
