# coding: utf-8

"""
    BambooHR API

    This is the majority of the API requests including some that are not documented.  http://www.bamboohr.com/api/documentation/

    The version of the OpenAPI document: v1
    Generated by: https://konfigthis.com
"""

import unittest

import bamboo_hr_python_sdk
from bamboo_hr_python_sdk.model.employee_deposit_accounts_item import EmployeeDepositAccountsItem
from bamboo_hr_python_sdk import configuration


class TestEmployeeDepositAccountsItem(unittest.TestCase):
    """EmployeeDepositAccountsItem unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
