# coding: utf-8

"""
    BambooHR API

    This is the majority of the API requests including some that are not documented.  http://www.bamboohr.com/api/documentation/

    The version of the OpenAPI document: v1
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict


class AdjustTimeOffBalance(BaseModel):
    # The date the adjustment should be added in history. Should be in ISO8601 date format (YYYY-MM-DD).
    date: str = Field(alias='date')

    # The ID of the time off type to add a balance adjustment for.
    time_off_type_id: int = Field(alias='timeOffTypeId')

    # The number of hours/days to adjust the balance by.
    amount: typing.Union[int, float] = Field(alias='amount')

    # This is an optional note to show in history.
    note: typing.Optional[str] = Field(None, alias='note')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
