# coding: utf-8

"""
    BambooHR API

    This is the majority of the API requests including some that are not documented.  http://www.bamboohr.com/api/documentation/

    The version of the OpenAPI document: v1
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from bamboo_hr_python_sdk.pydantic.applicant_tracking_get_application_details_response_moved_to_job_title import ApplicantTrackingGetApplicationDetailsResponseMovedToJobTitle

class ApplicantTrackingGetApplicationDetailsResponseMovedToJob(BaseModel):
    title: typing.Optional[ApplicantTrackingGetApplicationDetailsResponseMovedToJobTitle] = Field(None, alias='title')

    id: typing.Optional[typing.Union[int, float]] = Field(None, alias='id')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
