# coding: utf-8

"""
    BambooHR API

    This is the majority of the API requests including some that are not documented.  http://www.bamboohr.com/api/documentation/

    The version of the OpenAPI document: v1
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict


class BenefitGroupEmployee(BaseModel):
    benefit_group_id: typing.Optional[str] = Field(None, alias='benefitGroupId')

    employee_id: typing.Optional[str] = Field(None, alias='employeeId')

    start_date: typing.Optional[str] = Field(None, alias='startDate')

    end_date: typing.Optional[str] = Field(None, alias='endDate')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
