# coding: utf-8

"""
    BambooHR API

    This is the majority of the API requests including some that are not documented.  http://www.bamboohr.com/api/documentation/

    The version of the OpenAPI document: v1
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict


class BenefitGroupPlanCost(BaseModel):
    benefit_group_plan_id: typing.Optional[str] = Field(None, alias='benefitGroupPlanId')

    benefit_plan_coverage_id: typing.Optional[str] = Field(None, alias='benefitPlanCoverageId')

    employee_cost: typing.Optional[str] = Field(None, alias='employeeCost')

    company_cost: typing.Optional[str] = Field(None, alias='companyCost')

    start_date: typing.Optional[str] = Field(None, alias='startDate')

    end_date: typing.Optional[str] = Field(None, alias='endDate')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
