# coding: utf-8

"""
    BambooHR API

    This is the majority of the API requests including some that are not documented.  http://www.bamboohr.com/api/documentation/

    The version of the OpenAPI document: v1
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict


class GoalsGetGoalAggregateInfoResponseAlignsWithOptionsItem(BaseModel):
    # Title of the goal that the selected goal could be aligned with.
    title: typing.Optional[str] = Field(None, alias='title')

    # Id of the goal that the selected goal could be aligned with.
    id: typing.Optional[int] = Field(None, alias='id')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
