# coding: utf-8

"""
    BambooHR API

    This is the majority of the API requests including some that are not documented.  http://www.bamboohr.com/api/documentation/

    The version of the OpenAPI document: v1
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from bamboo_hr_python_sdk.pydantic.new_web_hook_frequency import NewWebHookFrequency
from bamboo_hr_python_sdk.pydantic.new_web_hook_limit import NewWebHookLimit
from bamboo_hr_python_sdk.pydantic.new_web_hook_monitor_fields import NewWebHookMonitorFields
from bamboo_hr_python_sdk.pydantic.new_web_hook_post_fields import NewWebHookPostFields

class NewWebHook(BaseModel):
    # The name of the webhook.
    name: str = Field(alias='name')

    monitor_fields: NewWebHookMonitorFields = Field(alias='monitorFields')

    post_fields: NewWebHookPostFields = Field(alias='postFields')

    # The url the webhook should send data to (must begin with https://).
    url: str = Field(alias='url')

    # The format the webhook should use (json - default, form-encoded).
    format: typing.Optional[Literal["json", "form-encoded"]] = Field(None, alias='format')

    frequency: typing.Optional[NewWebHookFrequency] = Field(None, alias='frequency')

    limit: typing.Optional[NewWebHookLimit] = Field(None, alias='limit')

    # If set to true, the company domain will be added to the header.
    include_company_domain: typing.Optional[bool] = Field(None, alias='includeCompanyDomain')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
