# coding: utf-8

"""
    BambooHR API

    This is the majority of the API requests including some that are not documented.  http://www.bamboohr.com/api/documentation/

    The version of the OpenAPI document: v1
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict


class TimeTrackingPrivateBetaAddEditHourEntriesRequestHoursItem(BaseModel):
    # Unique identifier for the employee.
    employee_id: int = Field(alias='employeeId')

    # Date for the timesheet entry. Must be in YYYY-MM-DD format.
    date: str = Field(alias='date')

    # Hours worked for this timesheet entry.
    hours: typing.Union[int, float] = Field(alias='hours')

    # The ID of an existing timesheet entry. This can be specified to edit an existing entry.
    id: typing.Optional[int] = Field(None, alias='id')

    # The ID of the project to associate with the timesheet entry.
    project_id: typing.Optional[int] = Field(None, alias='projectId')

    # The ID of the task to associate with the timesheet entry.
    task_id: typing.Optional[int] = Field(None, alias='taskId')

    # Optional note to associate with the timesheet entry.
    note: typing.Optional[str] = Field(None, alias='note')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
