# coding: utf-8

"""
    BambooHR API

    This is the majority of the API requests including some that are not documented.  http://www.bamboohr.com/api/documentation/

    The version of the OpenAPI document: v1
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from bamboo_hr_python_sdk.pydantic.time_off_request_dates import TimeOffRequestDates
from bamboo_hr_python_sdk.pydantic.time_off_request_notes import TimeOffRequestNotes

class TimeOffRequest(BaseModel):
    status: typing.Optional[str] = Field(None, alias='status')

    start: typing.Optional[str] = Field(None, alias='start')

    end: typing.Optional[str] = Field(None, alias='end')

    time_off_type_id: typing.Optional[int] = Field(None, alias='timeOffTypeId')

    amount: typing.Optional[int] = Field(None, alias='amount')

    notes: typing.Optional[TimeOffRequestNotes] = Field(None, alias='notes')

    dates: typing.Optional[TimeOffRequestDates] = Field(None, alias='dates')

    previous_request: typing.Optional[int] = Field(None, alias='previousRequest')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
