# coding: utf-8

"""
    BambooHR API

    This is the majority of the API requests including some that are not documented.  http://www.bamboohr.com/api/documentation/

    The version of the OpenAPI document: v1
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict


class TimeTrackingStoreClockEntriesRequestEntriesItem(BaseModel):
    # employee id for the time entry
    employee_id: typing.Optional[int] = Field(None, alias='employeeId')

    # date of the time entry
    date: typing.Optional[str] = Field(None, alias='date')

    # 24 hour format (hh:mm) for start time
    start: typing.Optional[str] = Field(None, alias='start')

    # 24 hour format (hh:mm) for end time
    end: typing.Optional[str] = Field(None, alias='end')

    # id of existing time entry. used when updating time entry
    clock_entry_id: typing.Optional[int] = Field(None, alias='clockEntryId')

    # The id of the project associated with the time entry
    project_id: typing.Optional[int] = Field(None, alias='projectId')

    # The id of the task associated with the time entry
    task_id: typing.Optional[int] = Field(None, alias='taskId')

    note: typing.Optional[str] = Field(None, alias='note')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
