# coding: utf-8

"""
    BambooHR API

    This is the majority of the API requests including some that are not documented.  http://www.bamboohr.com/api/documentation/

    The version of the OpenAPI document: v1
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict


class TrainingUpdateEmployeeTrainingRecordRequest(BaseModel):
    # Completed is the only required field and must be in yyyy-mm-dd format. The other parameters are optional.
    completed: str = Field(alias='completed')

    cost: typing.Optional[typing.Union[bool, date, datetime, dict, float, int, list, str, None]] = Field(None, alias='cost')

    instructor: typing.Optional[str] = Field(None, alias='instructor')

    hours: typing.Optional[typing.Union[int, float]] = Field(None, alias='hours')

    credits: typing.Optional[typing.Union[int, float]] = Field(None, alias='credits')

    notes: typing.Optional[typing.Union[int, float]] = Field(None, alias='notes')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
