from bamboo_hr_python_sdk.paths.company_domain_v1_performance_employees_employee_id_goals_goal_id_comments_comment_id.put import ApiForput
from bamboo_hr_python_sdk.paths.company_domain_v1_performance_employees_employee_id_goals_goal_id_comments_comment_id.delete import ApiFordelete


class CompanyDomainV1PerformanceEmployeesEmployeeIdGoalsGoalIdCommentsCommentId(
    ApiForput,
    ApiFordelete,
):
    pass
