# coding: utf-8

"""
    BambooHR API

    This is the majority of the API requests including some that are not documented.  http://www.bamboohr.com/api/documentation/

    The version of the OpenAPI document: v1
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from bamboo_hr_python_sdk.type.applicant_tracking_get_application_details_response_moved_to_job_title import ApplicantTrackingGetApplicationDetailsResponseMovedToJobTitle

class RequiredApplicantTrackingGetApplicationDetailsResponseMovedToJob(TypedDict):
    pass

class OptionalApplicantTrackingGetApplicationDetailsResponseMovedToJob(TypedDict, total=False):
    title: ApplicantTrackingGetApplicationDetailsResponseMovedToJobTitle

    id: typing.Union[int, float]

class ApplicantTrackingGetApplicationDetailsResponseMovedToJob(RequiredApplicantTrackingGetApplicationDetailsResponseMovedToJob, OptionalApplicantTrackingGetApplicationDetailsResponseMovedToJob):
    pass
