# coding: utf-8

"""
    BambooHR API

    This is the majority of the API requests including some that are not documented.  http://www.bamboohr.com/api/documentation/

    The version of the OpenAPI document: v1
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from bamboo_hr_python_sdk.type.applicant_tracking_get_application_details_response_moved_to_job import ApplicantTrackingGetApplicationDetailsResponseMovedToJob

class RequiredApplicantTrackingGetApplicationDetailsResponseMovedTo(TypedDict):
    pass

class OptionalApplicantTrackingGetApplicationDetailsResponseMovedTo(TypedDict, total=False):
    applicationId: typing.Union[int, float]

    job: ApplicantTrackingGetApplicationDetailsResponseMovedToJob

class ApplicantTrackingGetApplicationDetailsResponseMovedTo(RequiredApplicantTrackingGetApplicationDetailsResponseMovedTo, OptionalApplicantTrackingGetApplicationDetailsResponseMovedTo):
    pass
