# coding: utf-8

"""
    BambooHR API

    This is the majority of the API requests including some that are not documented.  http://www.bamboohr.com/api/documentation/

    The version of the OpenAPI document: v1
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredCompanyBenefitType(TypedDict):
    pass

class OptionalCompanyBenefitType(TypedDict, total=False):
    # The name of the company benefit plan.
    name: str

    # The unique identifier for the company benefit plan.
    slug: str

    # Can the company benefit plan be an ACA plan.
    canBeAcaPlan: bool

    # Can the company benefit plan co-exist with an enrollment plan.
    canCoExistEnrollment: bool

    # Is the company benefit plan a reimbursement plan.
    isReimbursementPlan: bool

class CompanyBenefitType(RequiredCompanyBenefitType, OptionalCompanyBenefitType):
    pass
