# coding: utf-8

"""
    BambooHR API

    This is the majority of the API requests including some that are not documented.  http://www.bamboohr.com/api/documentation/

    The version of the OpenAPI document: v1
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredCompanyBenefitResponse(TypedDict):
    pass

class OptionalCompanyBenefitResponse(TypedDict, total=False):
    # Description
    description: str

    # Name
    name: str

    # Benefit vendor ID
    benefitVendorId: str

    # Benefit type
    benefitType: str

    # Deduction type ID
    deductionTypeId: int

    # Benefit start date
    startDate: date

    # Benefit end date
    endDate: date

    # Plan url
    planUrl: str

    # SSO login url
    ssoLoginUrl: str

    # SSO login link text
    ssoLoginUrlLinkText: str

    # Is a safe harbor
    safeHarbor: str

    # Meets ACA minimum requirements
    meetAcaMin: str

    # Reimbursement amount
    reimbursementAmount: typing.Union[int, float]

    # Reimbursement frequency
    reimbursementFrequency: str

    # Provides minimum essential coverage
    minEssentialCoverage: str

class CompanyBenefitResponse(RequiredCompanyBenefitResponse, OptionalCompanyBenefitResponse):
    pass
