# coding: utf-8

"""
    BambooHR API

    This is the majority of the API requests including some that are not documented.  http://www.bamboohr.com/api/documentation/

    The version of the OpenAPI document: v1
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredEmployeeDependent(TypedDict):
    pass

class OptionalEmployeeDependent(TypedDict, total=False):
    employeeId: str

    firstName: str

    middleName: str

    lastName: str

    relationship: str

    gender: str

    ssn: str

    dateOfBirth: str

    addressLine1: str

    addressLine2: str

    city: str

    state: str

    zipCode: str

    homePhone: str

    country: str

    isUsCitizen: str

    isStudent: str

class EmployeeDependent(RequiredEmployeeDependent, OptionalEmployeeDependent):
    pass
