# coding: utf-8

"""
    BambooHR API

    This is the majority of the API requests including some that are not documented.  http://www.bamboohr.com/api/documentation/

    The version of the OpenAPI document: v1
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from bamboo_hr_python_sdk.type.goals_get_all_aggregate_info200_response_comments import GoalsGetAllAggregateInfo200ResponseComments
from bamboo_hr_python_sdk.type.goals_get_all_aggregate_info200_response_filters import GoalsGetAllAggregateInfo200ResponseFilters
from bamboo_hr_python_sdk.type.goals_get_all_aggregate_info200_response_goals import GoalsGetAllAggregateInfo200ResponseGoals
from bamboo_hr_python_sdk.type.goals_get_all_aggregate_info200_response_persons import GoalsGetAllAggregateInfo200ResponsePersons

class RequiredGoalsGetAllAggregateInfo200Response(TypedDict):
    pass

class OptionalGoalsGetAllAggregateInfo200Response(TypedDict, total=False):
    # The selected user can align goals with other users.
    canAlign: bool

    # The selected user can create a goal.
    canCreateGoals: bool

    filters: GoalsGetAllAggregateInfo200ResponseFilters

    # The id of the current selected filter.
    selectedFilter: str

    goals: GoalsGetAllAggregateInfo200ResponseGoals

    persons: GoalsGetAllAggregateInfo200ResponsePersons

    comments: GoalsGetAllAggregateInfo200ResponseComments

class GoalsGetAllAggregateInfo200Response(RequiredGoalsGetAllAggregateInfo200Response, OptionalGoalsGetAllAggregateInfo200Response):
    pass
