# coding: utf-8

"""
    BambooHR API

    This is the majority of the API requests including some that are not documented.  http://www.bamboohr.com/api/documentation/

    The version of the OpenAPI document: v1
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from bamboo_hr_python_sdk.type.goals_get_all_aggregate_info200_response1_goals_item_milestones_item import GoalsGetAllAggregateInfo200Response1GoalsItemMilestonesItem

GoalsGetAllAggregateInfo200Response1GoalsItemMilestones = typing.List[GoalsGetAllAggregateInfo200Response1GoalsItemMilestonesItem]
