# coding: utf-8

"""
    BambooHR API

    This is the majority of the API requests including some that are not documented.  http://www.bamboohr.com/api/documentation/

    The version of the OpenAPI document: v1
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredHiringLead(TypedDict):
    pass

class OptionalHiringLead(TypedDict, total=False):
    # The employeeId of the potential hiring lead
    employeeId: int

    # The preferred full name of the potential hiring lead
    preferredFullName: str

class HiringLead(RequiredHiringLead, OptionalHiringLead):
    pass
