# coding: utf-8

"""
    BambooHR API

    This is the majority of the API requests including some that are not documented.  http://www.bamboohr.com/api/documentation/

    The version of the OpenAPI document: v1
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from bamboo_hr_python_sdk.type.time_tracking_clock_in_employee_request_clock_in_location import TimeTrackingClockInEmployeeRequestClockInLocation

class RequiredTimeTrackingClockInEmployeeRequest(TypedDict):
    pass

class OptionalTimeTrackingClockInEmployeeRequest(TypedDict, total=False):
    # The start time for the clock in. In 24 hour format HH:MM
    start: str

    # The timezone associated with the clock in.
    timezone: str

    # The note associated with the clock in
    note: str

    # The id of the project associated with the clock in
    projectId: int

    # The id of the task associated with the clock in
    taskId: int

    clockInLocation: TimeTrackingClockInEmployeeRequestClockInLocation

class TimeTrackingClockInEmployeeRequest(RequiredTimeTrackingClockInEmployeeRequest, OptionalTimeTrackingClockInEmployeeRequest):
    pass
