# coding: utf-8

"""
    BambooHR API

    This is the majority of the API requests including some that are not documented.  http://www.bamboohr.com/api/documentation/

    The version of the OpenAPI document: v1
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from bamboo_hr_python_sdk.type.time_tracking_private_beta_create_project_task_request_employee_ids import TimeTrackingPrivateBetaCreateProjectTaskRequestEmployeeIds
from bamboo_hr_python_sdk.type.time_tracking_private_beta_create_project_task_request_tasks import TimeTrackingPrivateBetaCreateProjectTaskRequestTasks

class RequiredTimeTrackingPrivateBetaCreateProjectTaskRequest(TypedDict):
    # Name of the project.
    name: str

class OptionalTimeTrackingPrivateBetaCreateProjectTaskRequest(TypedDict, total=False):
    # Indicates if the project is billable. Defaults to true if not provided.
    billable: bool

    # Indicates if all employees can log time for this project. Defaults to true if not provided.
    allowAllEmployees: bool

    employeeIds: TimeTrackingPrivateBetaCreateProjectTaskRequestEmployeeIds

    # Indicates if the project has tasks. Defaults to false if not provided.
    hasTasks: bool

    tasks: TimeTrackingPrivateBetaCreateProjectTaskRequestTasks

class TimeTrackingPrivateBetaCreateProjectTaskRequest(RequiredTimeTrackingPrivateBetaCreateProjectTaskRequest, OptionalTimeTrackingPrivateBetaCreateProjectTaskRequest):
    pass
