# coding: utf-8

"""
    BambooHR API

    This is the majority of the API requests including some that are not documented.  http://www.bamboohr.com/api/documentation/

    The version of the OpenAPI document: v1
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredTrainingUpdateEmployeeTrainingRecordRequest(TypedDict):
    # Completed is the only required field and must be in yyyy-mm-dd format. The other parameters are optional.
    completed: str

class OptionalTrainingUpdateEmployeeTrainingRecordRequest(TypedDict, total=False):
    cost: typing.Union[bool, date, datetime, dict, float, int, list, str, None]

    instructor: str

    hours: typing.Union[int, float]

    credits: typing.Union[int, float]

    notes: typing.Union[int, float]

class TrainingUpdateEmployeeTrainingRecordRequest(RequiredTrainingUpdateEmployeeTrainingRecordRequest, OptionalTrainingUpdateEmployeeTrainingRecordRequest):
    pass
