# coding: utf-8

"""
    BambooHR API

    This is the majority of the API requests including some that are not documented.  http://www.bamboohr.com/api/documentation/

    The version of the OpenAPI document: v1
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from bamboo_hr_python_sdk.type.training_type_addition_request_category import TrainingTypeAdditionRequestCategory

class RequiredTrainingTypeAdditionRequest(TypedDict):
    # Name of the new training type.
    name: str

    # Is this a required training?
    required: bool

class OptionalTrainingTypeAdditionRequest(TypedDict, total=False):
    # Description for the training.
    description: str

    # The frequency is the (optional) amount of months between renewing trainings. Not valid if training are not renewable.
    frequency: int

    # Renewable is optional but if you are setting it to true you must pass a frequency which is the months between renewals.
    renewable: bool

    category: TrainingTypeAdditionRequestCategory

    # Number of days before the training is due for new hires. Not valid unless training is required.
    dueFromHireDate: int

    # Optional URL that can be included with a training.
    linkUrl: str

    # Allows all employees who can view the training to be able to mark it complete.
    allowEmployeesToMarkComplete: bool

class TrainingTypeAdditionRequest(RequiredTrainingTypeAdditionRequest, OptionalTrainingTypeAdditionRequest):
    pass
