# coding: utf-8

"""
    BambooHR API

    This is the majority of the API requests including some that are not documented.  http://www.bamboohr.com/api/documentation/

    The version of the OpenAPI document: v1
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from bamboo_hr_python_sdk.type.milestone import Milestone
from bamboo_hr_python_sdk.type.update_goal_v11_deleted_milestone_ids import UpdateGoalV11DeletedMilestoneIds
from bamboo_hr_python_sdk.type.update_goal_v11_shared_with_employee_ids import UpdateGoalV11SharedWithEmployeeIds

class RequiredUpdateGoalV11(TypedDict):
    # [Required] The goal title.
    title: str

    sharedWithEmployeeIds: UpdateGoalV11SharedWithEmployeeIds

    # [Required] The goal due date in YYYY-mm-dd format.
    dueDate: str

class OptionalUpdateGoalV11(TypedDict, total=False):
    # [Optional] The goal description.
    description: str

    # [Optional] The option ID that aligns with this goal.
    alignsWithOptionId: str

    # [Optional] A flag indicating whether or not milestones are enabled for this goal. Setting this flag to false will delete all existing milestones for this goal.
    milestonesEnabled: bool

    deletedMilestoneIds: UpdateGoalV11DeletedMilestoneIds

    # [Optional] All milestones to be added to the goal with this update.
    milestones: typing.List[Milestone]

class UpdateGoalV11(RequiredUpdateGoalV11, OptionalUpdateGoalV11):
    pass
