# coding: utf-8

"""
    BambooHR API

    This is the majority of the API requests including some that are not documented.  http://www.bamboohr.com/api/documentation/

    The version of the OpenAPI document: v1
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredWebHookResponseFrequency(TypedDict):
    pass

class OptionalWebHookResponseFrequency(TypedDict, total=False):
    # The hour to potentially fire.
    hour: int

    # The minute to potentially fire
    minute: int

    # The day to potentially fire
    day: int

    # The month to potentially fire
    month: typing.Union[bool, date, datetime, dict, float, int, list, str, None]

class WebHookResponseFrequency(RequiredWebHookResponseFrequency, OptionalWebHookResponseFrequency):
    pass
