# coding: utf-8

"""
    BambooHR API

    This is the majority of the API requests including some that are not documented.  http://www.bamboohr.com/api/documentation/

    The version of the OpenAPI document: v1
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from bamboo_hr_python_sdk.type.webhooks_add_new_webhook_response_frequency import WebhooksAddNewWebhookResponseFrequency
from bamboo_hr_python_sdk.type.webhooks_add_new_webhook_response_limit import WebhooksAddNewWebhookResponseLimit
from bamboo_hr_python_sdk.type.webhooks_add_new_webhook_response_monitor_fields import WebhooksAddNewWebhookResponseMonitorFields
from bamboo_hr_python_sdk.type.webhooks_add_new_webhook_response_post_fields import WebhooksAddNewWebhookResponsePostFields

class RequiredWebhooksAddNewWebhookResponse(TypedDict):
    pass

class OptionalWebhooksAddNewWebhookResponse(TypedDict, total=False):
    # The id of the webhook.
    id: int

    # The name of the webhook.
    name: str

    # timestamp of creation
    created: str

    # timestamp of last webhook sent
    lastSent: str

    monitorFields: WebhooksAddNewWebhookResponseMonitorFields

    postFields: WebhooksAddNewWebhookResponsePostFields

    # The url the webhook should send data to.
    url: str

    # The format the webhook should use (json, form-encoded).
    format: str

    frequency: WebhooksAddNewWebhookResponseFrequency

    limit: WebhooksAddNewWebhookResponseLimit

    # The private key which can be used to verify that the webhook is secure (uses HMAC-SHA256)
    privateKey: str

    # If set to true, the company domain will be added to the header.
    includeCompanyDomain: bool

class WebhooksAddNewWebhookResponse(RequiredWebhooksAddNewWebhookResponse, OptionalWebhooksAddNewWebhookResponse):
    pass
