# coding: utf-8

"""
    BambooHR API

    This is the majority of the API requests including some that are not documented.  http://www.bamboohr.com/api/documentation/

    The version of the OpenAPI document: v1
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from bamboo_hr_python_sdk.type.webhooks_add_new_webhook403_response_errors import WebhooksAddNewWebhook403ResponseErrors

class RequiredWebhooksAddNewWebhook403Response(TypedDict):
    pass

class OptionalWebhooksAddNewWebhook403Response(TypedDict, total=False):
    errors: WebhooksAddNewWebhook403ResponseErrors

class WebhooksAddNewWebhook403Response(RequiredWebhooksAddNewWebhook403Response, OptionalWebhooksAddNewWebhook403Response):
    pass
