# coding: utf-8

"""
    BambooHR API

    This is the majority of the API requests including some that are not documented.  http://www.bamboohr.com/api/documentation/

    The version of the OpenAPI document: v1
    Generated by: https://konfigthis.com
"""

from dataclasses import dataclass
import typing_extensions
import urllib3
from pydantic import RootModel
from bamboo_hr_python_sdk.request_before_hook import request_before_hook
import json
from urllib3._collections import HTTPHeaderDict

from bamboo_hr_python_sdk.api_response import AsyncGeneratorResponse
from bamboo_hr_python_sdk import api_client, exceptions
from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from bamboo_hr_python_sdk import schemas  # noqa: F401

from bamboo_hr_python_sdk.model.time_tracking_private_beta_create_project_task_request_employee_ids import TimeTrackingPrivateBetaCreateProjectTaskRequestEmployeeIds as TimeTrackingPrivateBetaCreateProjectTaskRequestEmployeeIdsSchema
from bamboo_hr_python_sdk.model.time_tracking_project_with_tasks_and_employee_ids import TimeTrackingProjectWithTasksAndEmployeeIds as TimeTrackingProjectWithTasksAndEmployeeIdsSchema
from bamboo_hr_python_sdk.model.time_tracking_private_beta_create_project_task_request_tasks import TimeTrackingPrivateBetaCreateProjectTaskRequestTasks as TimeTrackingPrivateBetaCreateProjectTaskRequestTasksSchema
from bamboo_hr_python_sdk.model.time_tracking_private_beta_create_project_task_request import TimeTrackingPrivateBetaCreateProjectTaskRequest as TimeTrackingPrivateBetaCreateProjectTaskRequestSchema

from bamboo_hr_python_sdk.type.time_tracking_private_beta_create_project_task_request import TimeTrackingPrivateBetaCreateProjectTaskRequest
from bamboo_hr_python_sdk.type.time_tracking_project_with_tasks_and_employee_ids import TimeTrackingProjectWithTasksAndEmployeeIds
from bamboo_hr_python_sdk.type.time_tracking_private_beta_create_project_task_request_tasks import TimeTrackingPrivateBetaCreateProjectTaskRequestTasks
from bamboo_hr_python_sdk.type.time_tracking_private_beta_create_project_task_request_employee_ids import TimeTrackingPrivateBetaCreateProjectTaskRequestEmployeeIds

from ...api_client import Dictionary
from bamboo_hr_python_sdk.pydantic.time_tracking_private_beta_create_project_task_request_tasks import TimeTrackingPrivateBetaCreateProjectTaskRequestTasks as TimeTrackingPrivateBetaCreateProjectTaskRequestTasksPydantic
from bamboo_hr_python_sdk.pydantic.time_tracking_private_beta_create_project_task_request import TimeTrackingPrivateBetaCreateProjectTaskRequest as TimeTrackingPrivateBetaCreateProjectTaskRequestPydantic
from bamboo_hr_python_sdk.pydantic.time_tracking_private_beta_create_project_task_request_employee_ids import TimeTrackingPrivateBetaCreateProjectTaskRequestEmployeeIds as TimeTrackingPrivateBetaCreateProjectTaskRequestEmployeeIdsPydantic
from bamboo_hr_python_sdk.pydantic.time_tracking_project_with_tasks_and_employee_ids import TimeTrackingProjectWithTasksAndEmployeeIds as TimeTrackingProjectWithTasksAndEmployeeIdsPydantic

# Path params
CompanyDomainSchema = schemas.StrSchema
RequestRequiredPathParams = typing_extensions.TypedDict(
    'RequestRequiredPathParams',
    {
        'companyDomain': typing.Union[CompanyDomainSchema, str, ],
    }
)
RequestOptionalPathParams = typing_extensions.TypedDict(
    'RequestOptionalPathParams',
    {
    },
    total=False
)


class RequestPathParams(RequestRequiredPathParams, RequestOptionalPathParams):
    pass


request_path_company_domain = api_client.PathParameter(
    name="companyDomain",
    style=api_client.ParameterStyle.SIMPLE,
    schema=CompanyDomainSchema,
    required=True,
)
# body param
SchemaForRequestBodyApplicationJson = TimeTrackingPrivateBetaCreateProjectTaskRequestSchema


request_body_time_tracking_private_beta_create_project_task_request = api_client.RequestBody(
    content={
        'application/json': api_client.MediaType(
            schema=SchemaForRequestBodyApplicationJson),
    },
)
SchemaFor201ResponseBodyApplicationJson = TimeTrackingProjectWithTasksAndEmployeeIdsSchema


@dataclass
class ApiResponseFor201(api_client.ApiResponse):
    body: TimeTrackingProjectWithTasksAndEmployeeIds


@dataclass
class ApiResponseFor201Async(api_client.AsyncApiResponse):
    body: TimeTrackingProjectWithTasksAndEmployeeIds


_response_for_201 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor201,
    response_cls_async=ApiResponseFor201Async,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor201ResponseBodyApplicationJson),
    },
)


@dataclass
class ApiResponseFor400(api_client.ApiResponse):
    body: schemas.Unset = schemas.unset


@dataclass
class ApiResponseFor400Async(api_client.AsyncApiResponse):
    body: schemas.Unset = schemas.unset


_response_for_400 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor400,
    response_cls_async=ApiResponseFor400Async,
)


@dataclass
class ApiResponseFor401(api_client.ApiResponse):
    body: schemas.Unset = schemas.unset


@dataclass
class ApiResponseFor401Async(api_client.AsyncApiResponse):
    body: schemas.Unset = schemas.unset


_response_for_401 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor401,
    response_cls_async=ApiResponseFor401Async,
)


@dataclass
class ApiResponseFor403(api_client.ApiResponse):
    body: schemas.Unset = schemas.unset


@dataclass
class ApiResponseFor403Async(api_client.AsyncApiResponse):
    body: schemas.Unset = schemas.unset


_response_for_403 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor403,
    response_cls_async=ApiResponseFor403Async,
)


@dataclass
class ApiResponseFor406(api_client.ApiResponse):
    body: schemas.Unset = schemas.unset


@dataclass
class ApiResponseFor406Async(api_client.AsyncApiResponse):
    body: schemas.Unset = schemas.unset


_response_for_406 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor406,
    response_cls_async=ApiResponseFor406Async,
)


@dataclass
class ApiResponseFor409(api_client.ApiResponse):
    body: schemas.Unset = schemas.unset


@dataclass
class ApiResponseFor409Async(api_client.AsyncApiResponse):
    body: schemas.Unset = schemas.unset


_response_for_409 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor409,
    response_cls_async=ApiResponseFor409Async,
)


@dataclass
class ApiResponseFor500(api_client.ApiResponse):
    body: schemas.Unset = schemas.unset


@dataclass
class ApiResponseFor500Async(api_client.AsyncApiResponse):
    body: schemas.Unset = schemas.unset


_response_for_500 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor500,
    response_cls_async=ApiResponseFor500Async,
)
_all_accept_content_types = (
    'application/json',
)


class BaseApi(api_client.Api):

    def _create_project_task_mapped_args(
        self,
        name: str,
        company_domain: str,
        billable: typing.Optional[bool] = None,
        allow_all_employees: typing.Optional[bool] = None,
        employee_ids: typing.Optional[TimeTrackingPrivateBetaCreateProjectTaskRequestEmployeeIds] = None,
        has_tasks: typing.Optional[bool] = None,
        tasks: typing.Optional[TimeTrackingPrivateBetaCreateProjectTaskRequestTasks] = None,
    ) -> api_client.MappedArgs:
        args: api_client.MappedArgs = api_client.MappedArgs()
        _path_params = {}
        _body = {}
        if name is not None:
            _body["name"] = name
        if billable is not None:
            _body["billable"] = billable
        if allow_all_employees is not None:
            _body["allowAllEmployees"] = allow_all_employees
        if employee_ids is not None:
            _body["employeeIds"] = employee_ids
        if has_tasks is not None:
            _body["hasTasks"] = has_tasks
        if tasks is not None:
            _body["tasks"] = tasks
        args.body = _body
        if company_domain is not None:
            _path_params["companyDomain"] = company_domain
        args.path = _path_params
        return args

    async def _acreate_project_task_oapg(
        self,
        body: typing.Any = None,
            path_params: typing.Optional[dict] = {},
        skip_deserialization: bool = True,
        timeout: typing.Optional[typing.Union[float, typing.Tuple]] = None,
        accept_content_types: typing.Tuple[str] = _all_accept_content_types,
        content_type: str = 'application/json',
        stream: bool = False,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor201Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        """
        Create a Time Tracking Project
        :param skip_deserialization: If true then api_response.response will be set but
            api_response.body and api_response.headers will not be deserialized into schema
            class instances
        """
        self._verify_typed_dict_inputs_oapg(RequestPathParams, path_params)
        used_path = path.value
    
        _path_params = {}
        for parameter in (
            request_path_company_domain,
        ):
            parameter_data = path_params.get(parameter.name, schemas.unset)
            if parameter_data is schemas.unset:
                continue
            serialized_data = parameter.serialize(parameter_data)
            _path_params.update(serialized_data)
    
        for k, v in _path_params.items():
            used_path = used_path.replace('{%s}' % k, v)
    
        _headers = HTTPHeaderDict()
        # TODO add cookie handling
        if accept_content_types:
            for accept_content_type in accept_content_types:
                _headers.add('Accept', accept_content_type)
        method = 'post'.upper()
        _headers.add('Content-Type', content_type)
    
        _fields = None
        _body = None
        request_before_hook(
            resource_path=used_path,
            method=method,
            configuration=self.api_client.configuration,
            path_template='/{companyDomain}/v1/time_tracking/projects',
            body=body,
            auth_settings=_auth,
            headers=_headers,
        )
        if body is not schemas.unset:
            serialized_data = request_body_time_tracking_private_beta_create_project_task_request.serialize(body, content_type)
            if 'fields' in serialized_data:
                _fields = serialized_data['fields']
            elif 'body' in serialized_data:
                _body = serialized_data['body']
    
        response = await self.api_client.async_call_api(
            resource_path=used_path,
            method=method,
            headers=_headers,
            fields=_fields,
            serialized_body=_body,
            body=body,
            auth_settings=_auth,
            timeout=timeout,
            **kwargs
        )
    
        if stream:
            if not 200 <= response.http_response.status <= 299:
                body = (await response.http_response.content.read()).decode("utf-8")
                raise exceptions.ApiStreamingException(
                    status=response.http_response.status,
                    reason=response.http_response.reason,
                    body=body,
                )
    
            async def stream_iterator():
                """
                iterates over response.http_response.content and closes connection once iteration has finished
                """
                async for line in response.http_response.content:
                    if line == b'\r\n':
                        continue
                    yield line
                response.http_response.close()
                await response.session.close()
            return AsyncGeneratorResponse(
                content=stream_iterator(),
                headers=response.http_response.headers,
                status=response.http_response.status,
                response=response.http_response
            )
    
        response_for_status = _status_code_to_response.get(str(response.http_response.status))
        if response_for_status:
            api_response = await response_for_status.deserialize_async(
                                                    response,
                                                    self.api_client.configuration,
                                                    skip_deserialization=skip_deserialization
                                                )
        else:
            # If response data is JSON then deserialize for SDK consumer convenience
            is_json = api_client.JSONDetector._content_type_is_json(response.http_response.headers.get('Content-Type', ''))
            api_response = api_client.ApiResponseWithoutDeserializationAsync(
                body=await response.http_response.json() if is_json else await response.http_response.text(),
                response=response.http_response,
                round_trip_time=response.round_trip_time,
                status=response.http_response.status,
                headers=response.http_response.headers,
            )
    
        if not 200 <= api_response.status <= 299:
            raise exceptions.ApiException(api_response=api_response)
    
        # cleanup session / response
        response.http_response.close()
        await response.session.close()
    
        return api_response


    def _create_project_task_oapg(
        self,
        body: typing.Any = None,
            path_params: typing.Optional[dict] = {},
        skip_deserialization: bool = True,
        timeout: typing.Optional[typing.Union[float, typing.Tuple]] = None,
        accept_content_types: typing.Tuple[str] = _all_accept_content_types,
        content_type: str = 'application/json',
        stream: bool = False,
    ) -> typing.Union[
        ApiResponseFor201,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        """
        Create a Time Tracking Project
        :param skip_deserialization: If true then api_response.response will be set but
            api_response.body and api_response.headers will not be deserialized into schema
            class instances
        """
        self._verify_typed_dict_inputs_oapg(RequestPathParams, path_params)
        used_path = path.value
    
        _path_params = {}
        for parameter in (
            request_path_company_domain,
        ):
            parameter_data = path_params.get(parameter.name, schemas.unset)
            if parameter_data is schemas.unset:
                continue
            serialized_data = parameter.serialize(parameter_data)
            _path_params.update(serialized_data)
    
        for k, v in _path_params.items():
            used_path = used_path.replace('{%s}' % k, v)
    
        _headers = HTTPHeaderDict()
        # TODO add cookie handling
        if accept_content_types:
            for accept_content_type in accept_content_types:
                _headers.add('Accept', accept_content_type)
        method = 'post'.upper()
        _headers.add('Content-Type', content_type)
    
        _fields = None
        _body = None
        request_before_hook(
            resource_path=used_path,
            method=method,
            configuration=self.api_client.configuration,
            path_template='/{companyDomain}/v1/time_tracking/projects',
            body=body,
            auth_settings=_auth,
            headers=_headers,
        )
        if body is not schemas.unset:
            serialized_data = request_body_time_tracking_private_beta_create_project_task_request.serialize(body, content_type)
            if 'fields' in serialized_data:
                _fields = serialized_data['fields']
            elif 'body' in serialized_data:
                _body = serialized_data['body']
    
        response = self.api_client.call_api(
            resource_path=used_path,
            method=method,
            headers=_headers,
            fields=_fields,
            serialized_body=_body,
            body=body,
            auth_settings=_auth,
            timeout=timeout,
        )
    
        response_for_status = _status_code_to_response.get(str(response.http_response.status))
        if response_for_status:
            api_response = response_for_status.deserialize(
                                                    response,
                                                    self.api_client.configuration,
                                                    skip_deserialization=skip_deserialization
                                                )
        else:
            # If response data is JSON then deserialize for SDK consumer convenience
            is_json = api_client.JSONDetector._content_type_is_json(response.http_response.headers.get('Content-Type', ''))
            api_response = api_client.ApiResponseWithoutDeserialization(
                body=json.loads(response.http_response.data) if is_json else response.http_response.data,
                response=response.http_response,
                round_trip_time=response.round_trip_time,
                status=response.http_response.status,
                headers=response.http_response.headers,
            )
    
        if not 200 <= api_response.status <= 299:
            raise exceptions.ApiException(api_response=api_response)
    
        return api_response


class CreateProjectTaskRaw(BaseApi):
    # this class is used by api classes that refer to endpoints with operationId fn names

    async def acreate_project_task(
        self,
        name: str,
        company_domain: str,
        billable: typing.Optional[bool] = None,
        allow_all_employees: typing.Optional[bool] = None,
        employee_ids: typing.Optional[TimeTrackingPrivateBetaCreateProjectTaskRequestEmployeeIds] = None,
        has_tasks: typing.Optional[bool] = None,
        tasks: typing.Optional[TimeTrackingPrivateBetaCreateProjectTaskRequestTasks] = None,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor201Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        args = self._create_project_task_mapped_args(
            name=name,
            company_domain=company_domain,
            billable=billable,
            allow_all_employees=allow_all_employees,
            employee_ids=employee_ids,
            has_tasks=has_tasks,
            tasks=tasks,
        )
        return await self._acreate_project_task_oapg(
            body=args.body,
            path_params=args.path,
            **kwargs,
        )
    
    def create_project_task(
        self,
        name: str,
        company_domain: str,
        billable: typing.Optional[bool] = None,
        allow_all_employees: typing.Optional[bool] = None,
        employee_ids: typing.Optional[TimeTrackingPrivateBetaCreateProjectTaskRequestEmployeeIds] = None,
        has_tasks: typing.Optional[bool] = None,
        tasks: typing.Optional[TimeTrackingPrivateBetaCreateProjectTaskRequestTasks] = None,
    ) -> typing.Union[
        ApiResponseFor201,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        args = self._create_project_task_mapped_args(
            name=name,
            company_domain=company_domain,
            billable=billable,
            allow_all_employees=allow_all_employees,
            employee_ids=employee_ids,
            has_tasks=has_tasks,
            tasks=tasks,
        )
        return self._create_project_task_oapg(
            body=args.body,
            path_params=args.path,
        )

class CreateProjectTask(BaseApi):

    async def acreate_project_task(
        self,
        name: str,
        company_domain: str,
        billable: typing.Optional[bool] = None,
        allow_all_employees: typing.Optional[bool] = None,
        employee_ids: typing.Optional[TimeTrackingPrivateBetaCreateProjectTaskRequestEmployeeIds] = None,
        has_tasks: typing.Optional[bool] = None,
        tasks: typing.Optional[TimeTrackingPrivateBetaCreateProjectTaskRequestTasks] = None,
        validate: bool = False,
        **kwargs,
    ) -> TimeTrackingProjectWithTasksAndEmployeeIdsPydantic:
        raw_response = await self.raw.acreate_project_task(
            name=name,
            company_domain=company_domain,
            billable=billable,
            allow_all_employees=allow_all_employees,
            employee_ids=employee_ids,
            has_tasks=has_tasks,
            tasks=tasks,
            **kwargs,
        )
        if validate:
            return TimeTrackingProjectWithTasksAndEmployeeIdsPydantic(**raw_response.body)
        return api_client.construct_model_instance(TimeTrackingProjectWithTasksAndEmployeeIdsPydantic, raw_response.body)
    
    
    def create_project_task(
        self,
        name: str,
        company_domain: str,
        billable: typing.Optional[bool] = None,
        allow_all_employees: typing.Optional[bool] = None,
        employee_ids: typing.Optional[TimeTrackingPrivateBetaCreateProjectTaskRequestEmployeeIds] = None,
        has_tasks: typing.Optional[bool] = None,
        tasks: typing.Optional[TimeTrackingPrivateBetaCreateProjectTaskRequestTasks] = None,
        validate: bool = False,
    ) -> TimeTrackingProjectWithTasksAndEmployeeIdsPydantic:
        raw_response = self.raw.create_project_task(
            name=name,
            company_domain=company_domain,
            billable=billable,
            allow_all_employees=allow_all_employees,
            employee_ids=employee_ids,
            has_tasks=has_tasks,
            tasks=tasks,
        )
        if validate:
            return TimeTrackingProjectWithTasksAndEmployeeIdsPydantic(**raw_response.body)
        return api_client.construct_model_instance(TimeTrackingProjectWithTasksAndEmployeeIdsPydantic, raw_response.body)


class ApiForpost(BaseApi):
    # this class is used by api classes that refer to endpoints by path and http method names

    async def apost(
        self,
        name: str,
        company_domain: str,
        billable: typing.Optional[bool] = None,
        allow_all_employees: typing.Optional[bool] = None,
        employee_ids: typing.Optional[TimeTrackingPrivateBetaCreateProjectTaskRequestEmployeeIds] = None,
        has_tasks: typing.Optional[bool] = None,
        tasks: typing.Optional[TimeTrackingPrivateBetaCreateProjectTaskRequestTasks] = None,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor201Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        args = self._create_project_task_mapped_args(
            name=name,
            company_domain=company_domain,
            billable=billable,
            allow_all_employees=allow_all_employees,
            employee_ids=employee_ids,
            has_tasks=has_tasks,
            tasks=tasks,
        )
        return await self._acreate_project_task_oapg(
            body=args.body,
            path_params=args.path,
            **kwargs,
        )
    
    def post(
        self,
        name: str,
        company_domain: str,
        billable: typing.Optional[bool] = None,
        allow_all_employees: typing.Optional[bool] = None,
        employee_ids: typing.Optional[TimeTrackingPrivateBetaCreateProjectTaskRequestEmployeeIds] = None,
        has_tasks: typing.Optional[bool] = None,
        tasks: typing.Optional[TimeTrackingPrivateBetaCreateProjectTaskRequestTasks] = None,
    ) -> typing.Union[
        ApiResponseFor201,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        args = self._create_project_task_mapped_args(
            name=name,
            company_domain=company_domain,
            billable=billable,
            allow_all_employees=allow_all_employees,
            employee_ids=employee_ids,
            has_tasks=has_tasks,
            tasks=tasks,
        )
        return self._create_project_task_oapg(
            body=args.body,
            path_params=args.path,
        )

