# coding: utf-8

"""
    BambooHR API

    This is the majority of the API requests including some that are not documented.  http://www.bamboohr.com/api/documentation/

    The version of the OpenAPI document: v1
    Generated by: https://konfigthis.com
"""

from bamboo_hr_python_sdk.paths.company_domain_v1_reports_id.get import CompanyReport
from bamboo_hr_python_sdk.paths.company_domain_v1_reports_custom.post import RequestCustomReport
from bamboo_hr_python_sdk.apis.tags.reports_api_raw import ReportsApiRaw


class ReportsApi(
    CompanyReport,
    RequestCustomReport,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: ReportsApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = ReportsApiRaw(api_client)
