# coding: utf-8

"""
    BambooHR API

    This is the majority of the API requests including some that are not documented.  http://www.bamboohr.com/api/documentation/

    The version of the OpenAPI document: v1
    Generated by: https://konfigthis.com
"""

from bamboo_hr_python_sdk.paths.company_domain_v1_time_tracking_timesheets_approve.post import ApproveEmployeeTimesheets
from bamboo_hr_python_sdk.paths.company_domain_v1_time_tracking_timesheets_clock_out_and_approve.post import ApproveEmployeeTimesheets0
from bamboo_hr_python_sdk.paths.company_domain_v1_time_tracking_clock_in_employee_id.post import ClockInEmployee
from bamboo_hr_python_sdk.paths.company_domain_v1_time_tracking_clock_out_employee_id.post import ClockOutEmployee
from bamboo_hr_python_sdk.paths.company_domain_v1_time_tracking_employee_employee_id_clock_out_datetime.post import ClockOutEmployeeAtSpecificTime
from bamboo_hr_python_sdk.paths.company_domain_v1_time_tracking_clock_entries.delete import DeleteClockEntries
from bamboo_hr_python_sdk.paths.company_domain_v1_time_tracking_employee_employee_id_clock_in_data.post import EditClockedInEntryData
from bamboo_hr_python_sdk.paths.company_domain_v1_time_tracking_employee_employee_id_is_clocked_in.get import EmployeeClockedIn
from bamboo_hr_python_sdk.paths.company_domain_v1_time_tracking_employee_employee_id_timesheet_timesheet_id.get import EmployeeTimesheetGet
from bamboo_hr_python_sdk.paths.company_domain_v1_time_tracking_employee_employee_id_clock_entries_id.get import GetClockEntry
from bamboo_hr_python_sdk.paths.company_domain_v1_time_tracking_employee_employee_id_daily_entries_id.get import GetDailyEntry
from bamboo_hr_python_sdk.paths.company_domain_v1_time_tracking_employee_employee_id_projects_project_id_tasks.get import GetProjectTasks
from bamboo_hr_python_sdk.paths.company_domain_v1_time_tracking_timesheets.get import GetTimesheetsByIds
from bamboo_hr_python_sdk.paths.company_domain_v1_time_tracking_employee_employee_id_projects.get import ListEmployeeProjects
from bamboo_hr_python_sdk.paths.company_domain_v1_time_tracking_clock_entries.post import StoreClockEntries
from bamboo_hr_python_sdk.paths.company_domain_v1_time_tracking_daily_entries.post import StoreDailyEntries
from bamboo_hr_python_sdk.apis.tags.time_tracking_api_raw import TimeTrackingApiRaw


class TimeTrackingApi(
    ApproveEmployeeTimesheets,
    ApproveEmployeeTimesheets0,
    ClockInEmployee,
    ClockOutEmployee,
    ClockOutEmployeeAtSpecificTime,
    DeleteClockEntries,
    EditClockedInEntryData,
    EmployeeClockedIn,
    EmployeeTimesheetGet,
    GetClockEntry,
    GetDailyEntry,
    GetProjectTasks,
    GetTimesheetsByIds,
    ListEmployeeProjects,
    StoreClockEntries,
    StoreDailyEntries,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: TimeTrackingApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = TimeTrackingApiRaw(api_client)
