# coding: utf-8

"""
    BambooHR API

    This is the majority of the API requests including some that are not documented.  http://www.bamboohr.com/api/documentation/

    The version of the OpenAPI document: v1
    Generated by: https://konfigthis.com
"""

from bamboo_hr_python_sdk.paths.company_domain_v1_employees_employee_id_time_off_history.put import AddTimeOffHistoryItemRaw
from bamboo_hr_python_sdk.paths.company_domain_v1_employees_employee_id_time_off_policies.put import AssignEmployeePoliciesRaw
from bamboo_hr_python_sdk.paths.company_domain_v1_1_employees_employee_id_time_off_policies.put import AssignEmployeePoliciesV11Raw
from bamboo_hr_python_sdk.paths.company_domain_v1_employees_employee_id_time_off_balance_adjustment.put import BalanceAdjustmentPutRaw
from bamboo_hr_python_sdk.paths.company_domain_v1_time_off_requests_request_id_status.put import ChangeRequestStatusRaw
from bamboo_hr_python_sdk.paths.company_domain_v1_employees_employee_id_time_off_calculator.get import EstimateFutureTimeOffBalancesRaw
from bamboo_hr_python_sdk.paths.company_domain_v1_meta_time_off_policies.get import GetPoliciesRaw
from bamboo_hr_python_sdk.paths.company_domain_v1_time_off_requests.get import GetTimeOffRequestsRaw
from bamboo_hr_python_sdk.paths.company_domain_v1_meta_time_off_types.get import GetTimeOffTypesRaw
from bamboo_hr_python_sdk.paths.company_domain_v1_time_off_whos_out.get import GetWhosOutListRaw
from bamboo_hr_python_sdk.paths.company_domain_v1_1_employees_employee_id_time_off_policies.get import ListEmployeePoliciesRaw
from bamboo_hr_python_sdk.paths.company_domain_v1_employees_employee_id_time_off_policies.get import ListEmployeeTimeOffPoliciesRaw
from bamboo_hr_python_sdk.paths.company_domain_v1_employees_employee_id_time_off_request.put import RequestCreationRaw


class TimeOffApiRaw(
    AddTimeOffHistoryItemRaw,
    AssignEmployeePoliciesRaw,
    AssignEmployeePoliciesV11Raw,
    BalanceAdjustmentPutRaw,
    ChangeRequestStatusRaw,
    EstimateFutureTimeOffBalancesRaw,
    GetPoliciesRaw,
    GetTimeOffRequestsRaw,
    GetTimeOffTypesRaw,
    GetWhosOutListRaw,
    ListEmployeePoliciesRaw,
    ListEmployeeTimeOffPoliciesRaw,
    RequestCreationRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
